### ISSUE TITLE
Links for in connectors description lead to not existing GitHub repos

### ISSUE THREAD

**Issue by ntimo** [socfortress/CoPilot#121]
**Describe the bug**
The Github links for the "Wazuh Worker Provisioning" & "Alert Creation Provisioning" mentioned in the description do not work, probably because the repo is private. 
![image](https://github.com/socfortress/CoPilot/assets/6145026/1a773a12-8e24-4feb-a8e8-520eefeda708)

**To Reproduce**

1. Open the connectors page
2. Try to follow the GitHub links in the description of "Wazuh Worker Provisioning" & "Alert Creation Provisioning"

**Expected behavior**
The links should work and not result in a dead end,

**Comment by taylorwalton** [comment]
Hey @ntimo - correct the repos are currently still private...will make public over the next few days and will release a video. Thanks for checking it out!
