### ISSUE TITLE
Error on login after initial setup

### ISSUE THREAD

**Issue by z00mz00m95** [socfortress/CoPilot#124]
Hello SOCFortress-Team,
Hello Taylor,

thank you for publishing this awesome project! After my first try i want to report a problem on initial setup.

**Error on login after initial setup**
Admin Credentials displaying - "An error occured. Please try again later."

**To Reproduce**
After setting up the Project with docker and editing the .env file with the api of the machine, the credentials are displayed in the log file of the container. These credentials are being used to try to log in.
The Frontend loads the request and displays the error with "An error occured. Please try again later."

This Problem also occurs when trying to register a new "user" with custom credentials.

**Expected behavior**
Login

**Comment by taylorwalton** [comment]
Have you set your server and VITE_API_URL IPs appropriately? Is the server listening on both ports `5000` and `5173`? Can you open your browsers development tools and share the network traffic?

**Comment by z00mz00m95** [comment]
Issue solved. Port 5000 blocked by network firewall. Thank you for the quick response!

**Comment by thisledome5** [comment]
this is closed, but I have now got this exact same issue.  My firewall currently is not active. I get exactly the same response as z00mz00m95   .. exactly how did you cure this issue
