### ISSUE TITLE
Make docker composo + repo readable

### ISSUE THREAD

**Issue by frikky** [socfortress/CoPilot#129]
Just an opinion to make things easier for people to understand:
- Clean up the repo root folder so we don't have to scroll before reaching the README (more files = less people finding README)
- Make a .env file and use that instead of all the environment variables in the docker-compose itself

Discard if you disagree

**Comment by taylorwalton** [comment]
Hey @frikky, thanks that makes sense and I will take a look! 

Regarding the `.env`, I have a `.env.example` which users need to copy to create their `.env` prior to starting the app. Is that what you were recommending and just didnt see the `.env.sample` file or are you referring to something different?

Thanks!

**Comment by frikky** [comment]
> Hey @frikky, thanks that makes sense and I will take a look!
> 
> Regarding the `.env`, I have a `.env.example` which users need to copy to create their `.env` prior to starting the app. Is that what you were recommending and just didnt see the `.env.sample` file or are you referring to something different?
> 
> Thanks!

My experience has been that .sample and .bak files are only used by powerusers (<1%), meaning they are basically useless, as those people figure it out anyway. It works that way if you manually reference it from the docker-compose tho (env_file: .env.example)

Just make things more readable by hiding gibberish most people don't need to read 🚒

**Comment by taylorwalton** [comment]
merged refactored branch with changes
