### ISSUE TITLE
Seperation of Frontend/Backend to distinct services for deployment

### ISSUE THREAD

**Issue by ChangingTerry** [socfortress/CoPilot#131]
I want to be able to deploy CoPilot behind a load balancer - as there is essentially two "services" running inside the Dockerfile (python backend and frontend server) this needs seperating or bundling togther with frontend router that can handle the backend.

**Describe the solution you'd like**
Ideally use vite to proxy calls to the backend so you can still use a single image - this would enable simplier control for CORS - or failing that two docker images

**Describe alternatives you've considered**
I tried looking at the code to see if I could change the backend port/starting but no joy

**Comment by taylorwalton** [comment]
Merged refactor branch with changes...closing for now but feel free to open another with any suggestions :)
