### ISSUE TITLE
An error occurred. Please try again later.

### ISSUE THREAD

**Issue by cybertricks** [socfortress/CoPilot#135]

**Comment by cybertricks** [comment]
<img width="577" alt="Screenshot 2024-02-08 at 11 55 22 PM" src="https://github.com/socfortress/CoPilot/assets/33148205/1c2316f8-3210-4c1b-82a8-47eba95ba6b2">

**Comment by taylorwalton** [comment]
@cybertricks can you try the latest build and let me know if still login issues?

**Comment by taylorwalton** [comment]
@mgarofano80 - what is your specific error? can you share your browser network tab?

**Comment by taylorwalton** [comment]
@mgarofano80 yup, as of now its hardset to 443...could you either stop that current service being served on 443 or start copilot on another server and retry?
