### ISSUE TITLE
Wazuh indexer integration error

### ISSUE THREAD

**Issue by mgarofano80** [socfortress/CoPilot#140]
I am getting the following error in the logs, when trying to load the Alerts pane, which remains empty:

"2024-02-09 20:47:35.981 | WARNING  | app.connectors.wazuh_indexer.services.alerts:get_alerts_generic:176 - Skipping index wazuh-alerts-4.x-2023.09.15 due to specific error: An error occurred while collecting alerts: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [timestamp_utc] in order to sort on')"

**Comment by taylorwalton** [comment]
@mgarofano80 this is expected because at socfortress we use the `timestamp_utc` field rather than the `timestamp` ... however, would you like the expect ability to use the default `timestamp` field?

**Comment by taylorwalton** [comment]
are you using Graylog as well?

**Comment by taylorwalton** [comment]
@mgarofano80 but shouldnt be too difficult to add as a search filter...created a feature request: https://github.com/socfortress/CoPilot/issues/141

**Comment by taylorwalton** [comment]
@mgarofano80 just pushed new copilot-backend image based off of these changes: https://github.com/socfortress/CoPilot/compare/main...enable-timefield

could you bring pull the latest image and restart and let me know?

```
docker pull ghcr.io/socfortress/copilot-backend:latest
```

**Comment by taylorwalton** [comment]
@mgarofano80 - have you had a chance to test this?

**Comment by taylorwalton** [comment]
closing but please recreate issue if your testing does not work out
