### ISSUE TITLE
Question: Copilot Scope

### ISSUE THREAD

**Issue by ZoccoCss** [socfortress/CoPilot#143]
My question is whether I need to create the connections between the different tools (for example the log ingestion for Graylog) or will Copilot take care of all the backend for me? 

I'm setting out an environment to test copilot. I'll be deploying Graylog, Velociraptor and Iris in a VM in Proxmox. I'm planning to use a Wazuh instance that I have already working in the network. 

In your Graylog install blog post you connect it to the Wazuh Indexer and I'm wondering whether this is necessary or not.

**Comment by taylorwalton** [comment]
Hey @ZoccoCss , yes you will still need to connect the tools to one another. For example, you will still need to connect the Fluent-bit running on the Wazuh-Manager to Graylog for event forwarding

**Comment by ZoccoCss** [comment]
Thank you @taylorwalton for your response. 

Based on the diagram from your blog post, I will also be making the following additional connections. 

-Grafana-Graylog-Wazuh
-Wazuh - Iris
-Iris - Velociraptor
-Graylog - OpenCTI
-Iris - MISP 

![SOC](https://github.com/socfortress/CoPilot/assets/47893772/d508dcc9-ce5d-4954-b698-d508f242de7d)

I'll wait for your instructions on how to integrate Shuffle, Cortex, Sublime and InfluxDB
