### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gustavohellwig** [socfortress/CoPilot#150]
Running the bash build-dockers.sh brings this:

![CoPilot](https://github.com/socfortress/CoPilot/assets/7680647/77a247d4-d9a7-49c4-ba95-695d285e102b)

Any suggestions? 
I did try on 2 different ubuntu servers (22.04.3 LTS)

- Linux 6.5.0-17-generic #17~22.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- Linux 5.15.0-89-generic #99-Ubuntu SMP aarch64 aarch64 aarch64 GNU/Linux

Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

**Comment by gustavohellwig** [comment]
I updated docker to 25 and it solved the problem. Maybe need to write that somewhere. Thank you !!!

**Comment by taylorwalton** [comment]
@gustavohellwig - i build the copilot-frontend now so you no longer have to do that
