### ISSUE TITLE
Velociraptor Artifacts don't report results when running Windows hunts

### ISSUE THREAD

**Issue by GeneBO98** [socfortress/CoPilot#155]
**Describe the bug**
If you are running a collect on an agent through the Velociraptor API it will run the hunt without issues. However, when you check to see what the results of the hunt were there are no results. This is not the case when running a Collect with Linux endpoints.
The issue wasn't experienced with all artifacts. I did see it with Windows.Events.TrackProcesses, Windows.Detection.Registry, and Windows.Analysis.EvidenceofDownload

**To Reproduce**

1. Go to Agents
2. Click on the agent you want to get further information on
3. Click on Collect and enter the Velociraptor Artifact and the VeloID
4. Select Submit and there is not a result, but the command does go through the Velociraptor

**Expected behavior**
To see the results of the velociraptor hunt either in the Collect pane or the Artifacts pane under the agent.

**Screenshots**
![image](https://github.com/socfortress/CoPilot/assets/60564320/f3c265b0-2454-4a85-94f2-e6e6f0ac3dc7)

\*\*Container Logs
[dockerlogs.txt](https://github.com/socfortress/CoPilot/files/14289701/dockerlogs.txt)

**Comment by taylorwalton** [comment]
hey @GeneBO98, could you share the results of the `Windows.Analysis.EvidenceofDownload` artifact collection through the Velociraptor web ui? I ran an evidence of download collection on a test windows box and all came through fine so im having trouble replicating your issue:

![image](https://github.com/socfortress/CoPilot/assets/111797488/d66d1611-848e-44f0-b293-5af5c8ec1863)

If you could share the json blob within the Velo web ui that would be helpful:

![image](https://github.com/socfortress/CoPilot/assets/111797488/4ce9ab31-15ad-4744-aa5c-bd4ebb081d09)

Thanks!

**Comment by GeneBO98** [comment]
I am attaching the .json file from the Artifact that was run.
[query_1.json](https://github.com/socfortress/CoPilot/files/14303531/query_1.json)

**Comment by taylorwalton** [comment]
hey @GeneBO98 im still having trouble replicating your issue...what version of velociraptor_server are you running?

**Comment by taylorwalton** [comment]
also have you pulled the latest release of the `copilot-backend` image?

**Comment by GeneBO98** [comment]
Velociraptor server is running version 0.7.1-1. I believe the backend is on the latest version, I pulled when before I submitted this issue, but I will pull once more.

**Comment by taylorwalton** [comment]
Could you shoot me a message on discord and we could find a time to meet so we can debug?

**Comment by taylorwalton** [comment]
@GeneBO98 any thoughts on this?

**Comment by GeneBO98** [comment]
It did seem to resolve the specific issues I was having with the latest image that was pulled through Docker.

**Comment by taylorwalton** [comment]
sorry meant for scheduling a session to troubleshoot...i still havent been able to successfully replicate on my end..the same artifact collection that is failing for you is working in my env

**Comment by vlados31999** [comment]
Hi, I have the same problem.
Commands on Velo are executed, but I don't see the result in CoPilot 
![image](https://github.com/socfortress/CoPilot/assets/104201717/d6cb7115-47c0-4af3-a1d0-722ebd4a9faf)
