### ISSUE TITLE
Update DFIR-IRIS client (version 2.0.1) to support IRIS last API version (2.0.5)

### ISSUE THREAD

**Issue by bronzato** [socfortress/CoPilot#168]
**Is your feature request related to a problem? Please describe.**
The connection with IRIS API is ok but when i click on SOC->Cases i got the following error:
Error creating session with DFIR-IRIS: Incompatible API version. Server expects 2.0.4 -> 2.0.5 but client is 2.0.1

**Describe the solution you'd like**
Update the iris client api to last version

**Describe alternatives you've considered**
propose a way to DIY

**Comment by taylorwalton** [comment]
What version of IRIS are you running?

**Comment by bronzato** [comment]
> What version of IRIS are you running?

Last version that documentation shows:
git checkout v2.3.7

**Comment by taylorwalton** [comment]
Yes, but did you also rebuild the image with the newly checked out repo? When you login to iris what does it show in the webui?

![image](https://github.com/socfortress/CoPilot/assets/111797488/dcf8745f-c612-42b6-8e24-a93e01a511f3)

**Comment by bronzato** [comment]
![image](https://github.com/socfortress/CoPilot/assets/6419694/035c5d59-dd6e-400f-94e1-e73b42150936)

**Comment by chadhardcastle** [comment]
I did some troubleshooting on my end today and can confirm that DFIR-IRIS 2.3.7 works fine with CoPilot, however when I upgraded to 2.4.5 it stopped working with the same error OP posted. On a separate unrelated note, the new version of IRIS also killed my Wazuh->Iris integration. 

Needless to say it looks like the API version compatibility will need to be updated on the CoPilot side.

**Comment by taylorwalton** [comment]
Is iris `2.4.5` offically released? Based on their latest release, the latest I see is `2.3.7`:

![image](https://github.com/socfortress/CoPilot/assets/111797488/c42c4a73-9835-456f-a234-54e89e6e7b43)

On their site, I also see docs havent been released yet (https://docs.dfir-iris.org/latest/operations/api/). I am hesitant to make compatible until documentation is provided:

![image](https://github.com/socfortress/CoPilot/assets/111797488/6a9a5e6b-d895-4f85-8f62-f5488d3968eb)

**Comment by taylorwalton** [comment]
closing for now...will revist when iris releases API docs

**Comment by SecurityArsenal** [comment]
They posted the docs: https://docs.dfir-iris.org/latest/_static/iris_api_reference_v2.0.4.html

**Comment by chadhardcastle** [comment]
I think this may have already been done. My updated deployment seems to work fine now.
