### ISSUE TITLE
InfluxDB connector incorrectly verifies

### ISSUE THREAD

**Issue by gap579137** [socfortress/CoPilot#169]
**Describe the bug**
The InfluxDB connector will  be "successfully configured" with any info given a correct URL, API Key and Extra Data do no matter as long as they are not blank

**To Reproduce**

1. Go to "Connectors"
2. Click on "Update" for the InfluxDB connector
3. Add a correct URL and anything in the API Key and Extra Data fields

**Expected behavior**
When saving the connector should verify an authorized connection otherwise should error out, possibly giving an explanation as to which field is incorrect

**Comment by taylorwalton** [comment]
Fixed in this commit: https://github.com/socfortress/CoPilot/commit/f8d2c3144f571d38ca6876cd3ff7be09e90a0ca5

Not apart of main yet but will be soon
