### ISSUE TITLE
Graylog Inputs Error

### ISSUE THREAD

**Issue by ZoccoCss** [socfortress/CoPilot#170]
**Describe the bug**
When I click on Graylog Inputs I receive the following error. 

![Screenshot_20240305_102239](https://github.com/socfortress/CoPilot/assets/47893772/c09e1979-f7c0-4fce-8fd9-292001055dcd)

**To Reproduce**

1. Go to Graylog tab
2. Scroll down and choose Management Submenu
3. On the Graylog/Management Menu click on  Inputs on the top right hand side
4. See error, the inputs are not shown. 

**Expected behavior**
I expected to see the inputs that I have in Graylog. In my case, these are my current inputs. 

![Screenshot_20240305_195140](https://github.com/socfortress/CoPilot/assets/47893772/9bbbb721-74ea-40a7-ab36-06e99c7838c7)

**Screenshots**
I configured the Graylog connector in the following way

![Screenshot_20240305_210523](https://github.com/socfortress/CoPilot/assets/47893772/77577939-a4fb-4460-9778-9f15dd18955f)

I am running a traefik proxy and I tried with and without the proxy for both Graylog and Copilot and I get the same error.

\*\*Container Logs

```
cd /opt/CoPilot
docker compose logs
```
Tail of the logs. In this case I was not using the reverse proxy. 

[copilot-docker-compose (1).tar.gz](https://github.com/socfortress/CoPilot/files/14503230/copilot-docker-compose.1.tar.gz)

**Comment by taylorwalton** [comment]
Fixed with this commit : https://github.com/socfortress/CoPilot/commit/9620bc44b922aa50fd514cb5849956d46fbdce7d

Fix will be available when `reporting` branch is merged into main
