### ISSUE TITLE
No alerts found and error messages

### ISSUE THREAD

**Issue by mgarofano80** [socfortress/CoPilot#176]
Hi, I just pulled the most recent docker image but I am still getting no alerts from Wazuh and the following error messages appear as soon as I launch the CoPIlot dashboard:

"Failed to send GET request to /api/system/pipelines/pipeline with error: Expecting value: line 1 column 1 (char 0)"

"Error fetching alerts: list index out of range"

Wazuh agents indeed are showing up and also the overall health of the Wazuh indexer cluster is deemed okay in the home screen.

**Comment by taylorwalton** [comment]
Hey @mgarofano80 do you have any Graylog pipelines defined? If you go into `System/Pipelines` with Graylog, what do you see?

Below is an example of mine:

![image](https://github.com/socfortress/CoPilot/assets/111797488/48e4f1f9-3ecd-4db6-ae4e-eac28478738c)

**Comment by taylorwalton** [comment]
This error ("Failed to send GET request to /api/system/pipelines/pipeline with error: Expecting value: line 1 column 1 (char 0)") only pertains to Graylog so if you arent running Graylog then you shouldnt be accessing the `Graylog` menu item within Copilot. Is that when you see the error?

Are you using the filter when searching for alerts or just loading the page? The page by default looks for logs where the `syslog_level` field is set to `ALERT` and if you are not using Graylog, you will not have that field name

**Comment by taylorwalton** [comment]
Well copilot needs to know what is your definition of an `alert`. This can be set via the `filter` button

![image](https://github.com/socfortress/CoPilot/assets/111797488/5a2599dd-a051-4800-86a6-84abccce8a82)

If one is not provided, it will default back to looking for events where the `syslog_level:ALERT`

**Comment by taylorwalton** [comment]
That top message pertains to Graylog and the `Error fetching alerts: list index out of range` message pertains to the InfluxDB connector. So if you dont have either of those tools, I'd expect those errors

**Comment by taylorwalton** [comment]
Could you try filtering for a specific `agent.name`? Could you send the logs of the docker container when you run the search?
