### ISSUE TITLE
Graylog Adapter missing files

### ISSUE THREAD

**Issue by deey001** [socfortress/CoPilot#182]
/etc/graylog/network_ports.csv "The path to the CSV file. The file does not exist."

/etc/graylog/software_vendors.csv "The path to the CSV file. The file does not exist."

/etc/graylog/nist_800_53_to_cui.csv "The path to the CSV file. The file does not exist."

Unable to signup for an API key for https://intel.socfortress.co/search?value=${key}

**Comment by taylorwalton** [comment]
Hey @deey001 thanks for installing the content pack.

Youre correct with the CSV files, you need to manually create these files on your Graylog server under `/etc/graylog/**CSV FILE**`

Here is an example blog post from Graylog: https://graylog.org/post/how-to-use-graylog-lookup-tables/

Currently our Threat Intel API is not available for public sign up, but we are currently working on it 👍

Best Regards,
Taylor
