### ISSUE TITLE
Failure to deploy stack on RHEL 9.3 and on Windows (using Docker Desktop)

### ISSUE THREAD

**Issue by european-dynamics-rnd** [socfortress/CoPilot#184]
**Describe the bug**
When I am trying to deploy the stack using docker I get the following error:
ERROR:    could not bind on any address out of [('10.250.100.13', 5000)]

I've checked if there are other services running there and there aren't. The VM is a fresh RHEL 9.3.

**Expected behavior**
CoPilot service should have spawned

**Screenshots**
![image](https://github.com/socfortress/CoPilot/assets/34477591/b6943b9b-e67e-49ad-8543-91a3853cc9e8)

\*\*Container Logs
WARN[0000] /opt/CoPilot/docker-compose.yml: `version` is obsolete
copilot-backend-1   | total 28
copilot-backend-1   | drwxr-xr-x  1 root root   18 Mar 29 06:38 .
copilot-backend-1   | drwxr-xr-x  1 root root   21 Mar 28 13:06 ..
copilot-backend-1   | -rw-r--r--  1 root root   27 Mar 28 13:06 .dockerignore
copilot-backend-1   | -rw-r--r--  1 root root 3129 Mar 28 13:06 Dockerfile
copilot-backend-1   | drwxr-xr-x 17 root root  294 Mar 28 13:06 app
copilot-backend-1   | -rw-r--r--  1 root root 5828 Mar 28 13:06 copilot.py
copilot-backend-1   | drwxr-xr-x  2 root root   24 Mar 28 15:56 data
copilot-backend-1   | drwxr-xr-x  2 root root    6 Mar 28 13:08 file-store
copilot-backend-1   | -rw-r--r--  1 root root  461 Mar 28 13:06 requirements.in
copilot-backend-1   | -rw-r--r--  1 root root 3089 Mar 28 13:06 requirements.txt
copilot-backend-1   | -rw-r--r--  1 root root 1083 Mar 28 13:06 settings.py
copilot-backend-1   | 2024-03-29 06:38:41.393 | INFO     | settings:<module>:16 - Loading environment from /opt/copilot/.env
copilot-backend-1   | INFO:     Started server process [7]
copilot-backend-1   | INFO:     Waiting for application startup.
copilot-backend-1   | 2024-03-29 06:38:44.945 | INFO     | app.db.db_setup:create_tables:28 - Creating tables
copilot-backend-1   | 2024-03-29 06:38:44.964 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Wazuh-Indexer from environment variables with URL: https://1.1.1.1:9200
copilot-backend-1   | 2024-03-29 06:38:44.965 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Wazuh-Manager from environment variables with URL: https://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.965 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Graylog from environment variables with URL: http://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.965 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Shuffle from environment variables with URL: https://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.965 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for DFIR-IRIS from environment variables with URL: https://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.966 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Velociraptor from environment variables with URL: https://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.966 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Sublime from environment variables with URL: http://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.966 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for InfluxDB from environment variables with URL: http://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.967 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for AskSocfortress from environment variables with URL: https://knowledge.socfortress.co
copilot-backend-1   | 2024-03-29 06:38:44.967 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for SocfortressThreatIntel from environment variables with URL: https://intel.socfortress.co/search
copilot-backend-1   | 2024-03-29 06:38:44.967 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Cortex from environment variables with URL: http://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.967 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Grafana from environment variables with URL: http://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.967 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Wazuh Worker Provisioning from environment variables with URL: http://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:44.967 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for Event Shipper from environment variables with URL: graylog_host
copilot-backend-1   | 2024-03-29 06:38:44.968 | INFO     | app.db.db_populate:load_connector_data:41 - Loading connector data for HAProxy Provisioning from environment variables with URL: http://1.1.1.1
copilot-backend-1   | 2024-03-29 06:38:45.060 | INFO     | app.db.db_setup:update_tables:48 - Updating tables
copilot-backend-1   | 2024-03-29 06:38:45.063 | INFO     | app.db.db_setup:update_tables:65 - Column extra_data TEXT already exists in scheduled_job_metadata
copilot-backend-1   | 2024-03-29 06:38:45.064 | INFO     | app.db.db_setup:update_tables:65 - Column wazuh_worker_hostname TEXT already exists in customer_provisioning_default_settings
copilot-backend-1   | 2024-03-29 06:38:45.065 | INFO     | app.db.db_setup:update_tables:65 - Column wazuh_agent_status TEXT already exists in agents
copilot-backend-1   | 2024-03-29 06:38:45.065 | INFO     | app.db.db_setup:create_roles:80 - Creating roles
copilot-backend-1   | 2024-03-29 06:38:45.066 | INFO     | app.db.db_populate:add_roles_if_not_exist:193 - Checking for existence of role admin
copilot-backend-1   | 2024-03-29 06:38:45.069 | INFO     | app.db.db_populate:add_roles_if_not_exist:193 - Checking for existence of role analyst
copilot-backend-1   | 2024-03-29 06:38:45.071 | INFO     | app.db.db_populate:add_roles_if_not_exist:193 - Checking for existence of role scheduler
copilot-backend-1   | 2024-03-29 06:38:45.072 | INFO     | app.db.db_populate:add_roles_if_not_exist:204 - Role check and addition completed.
copilot-backend-1   | 2024-03-29 06:38:45.073 | INFO     | app.db.db_setup:create_available_integrations:98 - Creating available integrations
copilot-backend-1   | 2024-03-29 06:38:45.073 | INFO     | app.db.db_populate:load_available_integrations_data:222 - Loading available integrations data for Office365.
copilot-backend-1   | 2024-03-29 06:38:45.073 | INFO     | app.db.db_populate:load_available_integrations_data:222 - Loading available integrations data for Mimecast.
copilot-backend-1   | 2024-03-29 06:38:45.074 | INFO     | app.db.db_populate:load_available_integrations_data:222 - Loading available integrations data for SAP SIEM.
copilot-backend-1   | 2024-03-29 06:38:45.074 | INFO     | app.db.db_populate:load_available_integrations_data:222 - Loading available integrations data for Huntress.
copilot-backend-1   | 2024-03-29 06:38:45.081 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Office365.
copilot-backend-1   | 2024-03-29 06:38:45.082 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Office365.
copilot-backend-1   | 2024-03-29 06:38:45.083 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Office365.
copilot-backend-1   | 2024-03-29 06:38:45.084 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Office365.
copilot-backend-1   | 2024-03-29 06:38:45.086 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Mimecast.
copilot-backend-1   | 2024-03-29 06:38:45.087 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Mimecast.
copilot-backend-1   | 2024-03-29 06:38:45.088 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Mimecast.
copilot-backend-1   | 2024-03-29 06:38:45.089 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Mimecast.
copilot-backend-1   | 2024-03-29 06:38:45.090 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Mimecast.
copilot-backend-1   | 2024-03-29 06:38:45.091 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for SAP SIEM.
copilot-backend-1   | 2024-03-29 06:38:45.092 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for SAP SIEM.
copilot-backend-1   | 2024-03-29 06:38:45.093 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for SAP SIEM.
copilot-backend-1   | 2024-03-29 06:38:45.094 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for SAP SIEM.
copilot-backend-1   | 2024-03-29 06:38:45.095 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Huntress.
copilot-backend-1   | 2024-03-29 06:38:45.096 | INFO     | app.db.db_populate:load_available_integrations_auth_keys:327 - Loading available integrations auth keys data for Huntress.
copilot-backend-1   | 2024-03-29 06:38:45.122 | INFO     | app.db.db_setup:ensure_admin_user:118 - Ensuring admin user exists
copilot-backend-1   | 2024-03-29 06:38:45.127 | INFO     | app.auth.services.universal:create_admin_user:127 - Admin user already exists.
copilot-backend-1   | 2024-03-29 06:38:45.128 | INFO     | app.db.db_setup:ensure_scheduler_user:135 - Ensuring scheduler user exists
copilot-backend-1   | 2024-03-29 06:38:45.489 | INFO     | app.auth.services.universal:create_scheduler_user:157 - Added new scheduler user with username: scheduler
copilot-backend-1   | 2024-03-29 06:38:45.489 | INFO     | app.auth.services.universal:create_scheduler_user:158 - Scheduler user password: m;M?}j$v91"d
copilot-backend-1   | 2024-03-29 06:38:45.500 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:109 - Scheduled job: agent_sync
copilot-backend-1   | 2024-03-29 06:38:45.507 | INFO     | __main__:init_db:146 - Starting scheduler
copilot-backend-1   | INFO:     Application startup complete.
copilot-backend-1   | ERROR:    could not bind on any address out of [('10.250.100.13', 5000)]
copilot-backend-1   | INFO:     Waiting for application shutdown.
copilot-backend-1   | 2024-03-29 06:38:45.511 | INFO     | __main__:shutdown_scheduler:158 - Shutting down scheduler
copilot-backend-1   | 2024-03-29 06:38:45.515 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:109 - Scheduled job: agent_sync
copilot-backend-1   | 2024-03-29 06:38:45.521 | INFO     | app.db.db_setup:ensure_scheduler_user_removed:152 - Ensuring scheduler user exists
copilot-backend-1   | 2024-03-29 06:38:45.534 | INFO     | app.auth.services.universal:remove_scheduler_user:185 - Scheduler user removed.
copilot-backend-1   | INFO:     Application shutdown complete.
copilot-frontend-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
copilot-frontend-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
copilot-frontend-1  | 10-listen-on-ipv6-by-default.sh: info: ipv6 not available
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
copilot-frontend-1  | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-copilot-ssl.sh
copilot-frontend-1  | Host is now https://localhost:
copilot-frontend-1  | No TLS certs found. Generating....
copilot-frontend-1  | ....+.+......+..+...+...+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+............+..........+...........+....+............+.....+....+..............+.......+......+........+......+.+.........+......+........+.+...........+.......+..+....+.........+...........+.+...+......+..+..........+...+.....+..........+..+....+.....+.............+.................+...+...............+..................+.........+..........+..............+.+...+........+....+......+............+.....+............+......+....+.........+..+...+......+....+....................+.......+.....+.......+......+.....+....+......+........................+...+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
copilot-frontend-1  | .+................+.........+.....+.+..+...+......+...............+......+...+.+.....+......+....+...+..+....+.........+...............+...............+...+..+.......+...+..+....+......+........+.+...........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...............+.+............+..+......+.+...+.....+.............+.........+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+.............+...+...........+......+......................+.....+..........+..+....+.........+........+.........+................+.....+...+.........+..........+........+...+.......+................................+.+.....+.+.....+..............................................+........+........................+.......+......+.........+.....+.+........+............+.......+..................+..............+....+......+.....+......+....+...+.....+...+..................+...............+.........+.......+......+............+...+.....+.......+..+...+.+.........+.....+......+.+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
copilot-frontend-1  | -----
copilot-frontend-1  | Generating new DH parameters - this may take a while...
copilot-frontend-1  | Generating DH parameters, 2048 bit long safe prime
copilot-frontend-1  | ...........................+...............................................................................................................+................................................................................................+..............................................................................................................................................................................................................................................................+......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................+...................................................................................................................................................................................................................................................................................................................................................................+............................................................................................................................................................+...............................................+........................................+...............................+.................+...........................................................................................................................................................................................+...............................................................................................+.................................................................................................................................................................................................................+.......................................................................................................................................................+...........................................................................................................................+.........................................................................................................................................................................................................+.............................+...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................+.................+.............................................................................................................................................................................+..................................................+...................................................................................................................................................+........................................................................................................................................................................................................+.........................................................................................................................+............................................................................+..........................................................................................................................+.........................................................................................................................................................................................................+...........................................+.............................+..............................+.........................................++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*
copilot-frontend-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend-1  | 2024/03/28 15:56:07 [emerg] 1#1: host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62
copilot-frontend-1  | nginx: [emerg] host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62
copilot-frontend-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
copilot-frontend-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
copilot-frontend-1  | 10-listen-on-ipv6-by-default.sh: info: ipv6 not available
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
copilot-frontend-1  | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-copilot-ssl.sh
copilot-frontend-1  | Host is now https://localhost:
copilot-frontend-1  | TLS certificates found
copilot-frontend-1  | ... DH parameters found
copilot-frontend-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend-1  | 2024/03/28 15:56:20 [emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)
copilot-frontend-1  | nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
copilot-frontend-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
copilot-frontend-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
copilot-frontend-1  | 10-listen-on-ipv6-by-default.sh: info: ipv6 not available
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
copilot-frontend-1  | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-copilot-ssl.sh
copilot-frontend-1  | Host is now https://localhost:
copilot-frontend-1  | TLS certificates found
copilot-frontend-1  | ... DH parameters found
copilot-frontend-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend-1  | 2024/03/28 15:56:43 [emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)
copilot-frontend-1  | nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
copilot-frontend-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
copilot-frontend-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
copilot-frontend-1  | 10-listen-on-ipv6-by-default.sh: info: ipv6 not available
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
copilot-frontend-1  | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-copilot-ssl.sh
copilot-frontend-1  | Host is now https://localhost:
copilot-frontend-1  | TLS certificates found
copilot-frontend-1  | ... DH parameters found
copilot-frontend-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend-1  | 2024/03/29 06:38:40 [emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)
copilot-frontend-1  | nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

**Comment by taylorwalton** [comment]
@european-dynamics-rnd Hey there, what does your `.env` file look like?

**Comment by european-dynamics-rnd** [comment]
I have used the one you provided and only changed the SERVER_IP to the one my VM. So in my case
SERVER_IP=10.250.100.13

**Comment by taylorwalton** [comment]
Try leaving that to `0.0.0.0`

**Comment by european-dynamics-rnd** [comment]
CoPilot backend is fine. Front end after a while exits with:
copilot-frontend-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
copilot-frontend-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
copilot-frontend-1  | 10-listen-on-ipv6-by-default.sh: info: ipv6 not available
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
copilot-frontend-1  | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
copilot-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-copilot-ssl.sh
copilot-frontend-1  | Host is now https://localhost:
copilot-frontend-1  | No TLS certs found. Generating....
copilot-frontend-1  | .........+..+.+..+.........+...+.+..+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+...+.......+...+..+......+...+.+........+...+...+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*......+.............+..............+.......+...+.....+......+....+..........................+....+..+......+...+.+...+.......................+.......+...........+.+.........+.....................+.....+...+......+.........+......+......+.+...+...........+.....................+...+.........+.+..+...+.+.........+.......................................+...+..............+......+.......+......+......+........+...+....+........+.+............+.....+...+...................+......+..+.........+......+......................+...........+.+...+.....+............+.+..+.+.........+.................+...............+.+...+......+...+..................+...+..+...+.........+.......+.....+......+.........+...+...+..........+...+.....+......+...+............+..........+...........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
copilot-frontend-1  | .....+......+...+.+......+...+.....+...+.......+...........+.......+..+............+.........+.+...+........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.......+.........+.+..+...+.+...+...+.........+......+.....+.............+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+...+.......+...+.........+.....+...+.......+......+...+.....+......................+...............+............+......+.....+.+...........+...+.+.....+..........+.....+...+......+.+...+..+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
copilot-frontend-1  | -----
copilot-frontend-1  | Generating new DH parameters - this may take a while...
copilot-frontend-1  | Generating DH parameters, 2048 bit long safe prime
copilot-frontend-1  | .................................................................+.................................................................................................................................................................................+.........................................................+


copilot-frontend-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend-1  | 2024/03/29 14:24:25 [emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)
copilot-frontend-1  | nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

**Comment by taylorwalton** [comment]
Maybe try commenting out the bind to port `80` in the compose file?

**Comment by european-dynamics-rnd** [comment]
Even after commenting (#- "80:80") port 80 in the docker-compose.yml I still get the same error. Maybe I am doing it in the wrong place?

**Comment by taylorwalton** [comment]
Why did you set to `10.0.0.0`?

**Comment by european-dynamics-rnd** [comment]
yes my mistake. Summary:
On my Windows machine the CoPilot stack deployed fine and accessed it on my browser (https://localhost/login)
On my RHEL machine it fails with:
copilot-frontend-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend-1  | 2024/03/29 14:36:20 [emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)
copilot-frontend-1  | nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

**Comment by european-dynamics-rnd** [comment]
Thank you so much for the immediate support. I will ask my sysadmins to replace the VM with a debian based one and let you know how it goes. Have a nice weekend. 
Alkis

**Comment by taylorwalton** [comment]
Will close for now, but will reopen if you see problem again
