### ISSUE TITLE
timestamp parse error on CoPilot 

### ISSUE THREAD

**Issue by mrmrspace1** [socfortress/CoPilot#186]
I am getting the following error in the logs, when trying to load the Alerts pane, which remains empty:

"2024-02-09 20:47:35.981 | WARNING | app.connectors.wazuh_indexer.services.alerts:get_alerts_generic:176 - Skipping index wazuh-alerts-4.x-2023.09.15 due to specific error: An error occurred while collecting alerts: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [timestamp_utc] in order to sort on')"

after docker pull update not working correctly again

**Comment by mrmrspace1** [comment]
Also for specific index

An error occurred while processing index .siem-signals-default-000012: An error occurred while collecting alerts: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [timestamp] in order to sort on')

**Comment by taylorwalton** [comment]
Are you using the filter when searching for alerts or just loading the page? The page by default looks for logs where the syslog_level field is set to ALERT and if you are not using Graylog, you will not have that field name. Please see https://github.com/socfortress/CoPilot/issues/176 for setting a filter

**Comment by mrmrspace1** [comment]
Thanks for the response, I have configured wazuh-index and wazuh-manager on copilot I am getting alerts from elasticsearch and wazuh manager everything working and looks good, I see index names and everything on copilot dashboard ,  but unfortunately alerts doesn't seem  on copilot dashboard from elastic Search ,always errors like on my dashboard, 'No mapping found for [timestamp] in order to sort on')

**Comment by taylorwalton** [comment]
What filter have you set? can you paste the raw json of one the the elasticsearch documents you would expect to see appear within the alerts pane?

**Comment by taylorwalton** [comment]
@mrghost100348 looks like the difference is you have `@timestamp` while when using Graylog, I have `timestamp`

![image](https://github.com/socfortress/CoPilot/assets/111797488/85011c0d-3e99-4d69-b34d-3ee0a22607dd)

Ill see if I can add a fallback to use `@timestamp` if `timestamp` is not found...ill update here when ive pushed the attempted fix

**Comment by taylorwalton** [comment]
@mrghost100348 please pull latest backend image and try again and let me know

**Comment by taylorwalton** [comment]
Thanks @mrghost100348 for the analysis...in the latest code change I added the `filebeat` index to the list of index names to be skipped when alerts are collected
