### ISSUE TITLE
"HAProxy" error after updating

### ISSUE THREAD

**Issue by mgarofano80** [socfortress/CoPilot#188]
After updating to the most recent CoPilot image by using the described method (docker compose pull), I am getting the following error:

copilot-backend-1   | [parameters: ('HAProxy Provisioning', '3', None, '2024-04-03 23:43:16.463267', None, None, None, 'Connection to HAProxy Provisioning. Make sure you have deployed the HAProxy Provisioning Application provided by SOCFortress: https://github.com/socfortress/Customer-Provisioning-Worker', 'Not specified.', 1, 0, 1, 0, 0, 0, 0, None)]
copilot-backend-1   | (Background on this error at: https://sqlalche.me/e/14/gkpj)
copilot-backend-1   | 
copilot-backend-1   | ERROR:    Application startup failed. Exiting.
copilot-backend-1 exited with code 3
copilot-frontend-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend-1  | 2024/04/03 23:43:22 [emerg] 1#1: host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62
copilot-frontend-1  | nginx: [emerg] host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62
copilot-frontend-1 exited with code 1

Please note that the URL "https://github.com/socfortress/Customer-Provisioning-Worker" returns an error.

**Comment by Stuw** [comment]
Same as #187

**Comment by taylorwalton** [comment]
Hey @mgarofano80  please add this in your `.env` : `HAPROXY_PROVISIONING_URL=http://1.1.1.1`

See the `.env.example` here: https://github.com/socfortress/CoPilot/blob/main/.env.example
