### ISSUE TITLE
Upgrade DFIR-IRIS Client

### ISSUE THREAD

**Issue by taylorwalton** [socfortress/CoPilot#189]
Bump DFIR-CLIENT to 2.0.4:

https://docs.dfir-iris.org/latest/_static/iris_api_reference_v2.0.4.html

**Comment by taylorwalton** [comment]
Had to open issue with DFIR-IRIS to address bug: https://github.com/dfir-iris/iris-web/issues/458

**Comment by taylorwalton** [comment]
Above issue, is not a bug. Newest version of IRIS requires the user to be added to the customer. Added logic to add the user to the customer as apart of the customer provisioning process. Need to take a look at `Notes` feature as that appears to have changed

**Comment by taylorwalton** [comment]
Bumped IRIS client to 2.0.4

**Comment by SecurityArsenal** [comment]
An easy for now is to edit iris source and build new image:  
edit /opt/iris-web/source/app/configuration.py  
Change:
 API_MAX_VERSION = "2.0.4"

This gets around the error.
