### ISSUE TITLE
Copilot Backend Crash after latest update

### ISSUE THREAD

**Issue by mrghost100348** [socfortress/CoPilot#200]
**Describe the bug**
Previously I was running version of CoPilot which doesn't have MySQL involved. In docker-compose file there was only two images frontend and backend. This version was running smoothly without any isues.
Today I saw there was recent update for copilot-backend image 14 hours ago. So I just did docker-compose pull to update the image and it crashed the container. I tried reinstalling the Copilot from scratch but it is still crashing and Backend container is not starting. I haved attached docker logs for more details.

**Note**

- The README.md providing link to the docker-compose.yml file [v0.0.7](https://raw.githubusercontent.com/socfortress/CoPilot/v0.0.7/docker-compose.yml) doesn't contain mysql image. 
- But it is fetching latest version of docker-image which is updated 14 hours ago.
- To fix the issue I manually updated [my docker-compose.yml](https://raw.githubusercontent.com/socfortress/CoPilot/v0.0.7/docker-compose.yml) to the latest [2 days ago docker-compsoe.yml](https://github.com/socfortress/CoPilot/blob/main/docker-compose.yml) available in github repo.
- Also I updated my .env whith latest [2 days ago one](https://github.com/socfortress/CoPilot/blob/main/.env.example).
- But still I am facing the issue.

**To Reproduce**
1. docker-compose down
2. docker-compose pull 
3. docker-compose up -d

or Install latest version from scratch

**Expected behavior**
Copilot Backend should communicate with MySQL and run without crashing or errors. It should allow user to log in.

\*\*Container Logs

```
[_copilot_copilot-backend_1_logs.txt](https://github.com/socfortress/CoPilot/files/15108658/_copilot_copilot-backend_1_logs.txt)

```

Edit:

I tried multiple ways to resolve the issue by installing on different servers and here are the updated docker logs where it is facing issue of Access Denied to MySQL user.

**Backend Logs:**
[_copilot_copilot-backend_1_logs_updated.txt](https://github.com/socfortress/CoPilot/files/15109039/_copilot_copilot-backend_1_logs_updated.txt)

**MySQL Logs:**
[_copilot_copilot-mysql_1_logs_updated.txt](https://github.com/socfortress/CoPilot/files/15109041/_copilot_copilot-mysql_1_logs_updated.txt)

**Comment by kmendell** [comment]
i had something like this happen as well i downloaded we the containers and then did docker system prune -a and the docker volume prune -a and the. tried to restart the containers and it worked for me
