### ISSUE TITLE
mySQL - a new requirement?

### ISSUE THREAD

**Issue by kschleelein** [socfortress/CoPilot#203]
**Describe the bug**
So is mySQL now a requirement like docker and docker compose? Or is this something still being worked on? I only ask because after rebuilding my server with the latest image, I cannot log in the the admin/generated password and I am wondering if it is because the DB is not online or is it something else.

**To Reproduce**

**Expected behavior**

**Screenshots**

\*\*Container Logs

```
cd /opt/CoPilot
docker compose logs
```

**Comment by taylorwalton** [comment]
Hey there, yes MySQL is new requirement:

Docker-compose: https://github.com/socfortress/CoPilot/blob/main/docker-compose.yml

![image](https://github.com/socfortress/CoPilot/assets/111797488/cec9eaa0-f52e-4864-aba9-f1e6b6458d28)
