### ISSUE TITLE
Connection URL

### ISSUE THREAD

**Issue by snis** [socfortress/CoPilot#205]
**Describe the bug**
My CoPilot container runs on the same Docker network as my Wazuh and Graylog containers (small lab setup). When trying to add (for example) my Graylog as a "connector" I add 'http://graylog:9000' (containers name is graylog), but that is not a valid URL.

**To Reproduce**
Add connector by its hostname without DNS suffix

**Expected behavior**
Let me choose the URL. ;)
I would like to not have to use Docker exposed ports, but keep the traffic internal.

Thanks

**Comment by taylorwalton** [comment]
Hey @snis - thanks for detailing your issue. I agree, this is a limitation that I can see impacting docker deployments. I will look to get fix implemented over the next few days.

Best Regards,
Taylor

**Comment by snis** [comment]
Another thought i had, in the .env.example file you have put 1.1.1.1 as a dummy connector address, doesn't that mean that CoPilot tries to connect to 1.1.1.1.
Would be better with 127.1.1.1 (or any 127.0.0.0/8, yes they all works to ping on Linux anyway) address that leads to localhost and not out on the scary Internet.
