### ISSUE TITLE
Synchronize Wazuh and Velociraptor devices using another ID, not the device's hostname/name

### ISSUE THREAD

**Issue by igorcantarelli** [socfortress/CoPilot#209]
I was installing Velociraptor on some devices that had Wazuh Agent installed, and they weren't synchronizing in the "Agents" tab. Looking at the logs, I realized that I would necessarily need to have the same device name that I have in wazuh, in velociraptor. It would be interesting to have another method of linking the velociraptor devices to wazuh, perhaps by taking the hostname via copilot and applying it to the host with the different name

**Comment by taylorwalton** [comment]
Hey @igorcantarelli you are correct in identifying that the hostname of the wazuh agent and the hostname of the velociraptor agent must match for copilot to be able to retrieve both the wazuh agent metadata and the velo agent details. Can I ask why your endpoint's hostname is different between wazuh and velo? Both agents should enumerate the same hostname when installed and I have yet to run across the agent collecting different hostname myself.

What we can employ is the ability to manually set the `velociraptor_id` for the agent via the UI if it was not collected. What do you think?

**Comment by igorcantarelli** [comment]
Hello, @taylorwalton! First of all, thanks for the quick reply.

I'm using velociraptor for the first time, but from the little I've used it, it seems that there is no option to customize the hostname, it automatically takes the hostname of the device, correct?
My problem with this is that I have several devices with the same hostname, without a local domain to differentiate them (multiples dc01 for example), so I believe that this would cause conflicts in the future (at least in the organization and identification of the devices).

The idea of making fields customizable is excellent!

Thanks again for the feedback.

**Comment by taylorwalton** [comment]
Hey @igorcantarelli - that is correct, velociraptor automatically takes the hostname of the device. If you have multiple devices with the same hostname, are you also having issues getting them enrolled with the wazuh manager? If you do not employ local domains, how do you manage and differentiate between these servers? Is this a production environment?

**Comment by igorcantarelli** [comment]
To register with wazuh-manager I used to change the agent name when registering, so it would allow me to log in even if the device had the same hostname. We have a wazuh in production, but we're redesigning the soc, so we're going to do all the installations from scratch. In addition, we're going to put all the tools in dockers, are there any known difficulties in integrating the tools in docker with copilot?

Thank you!

**Comment by taylorwalton** [comment]
Latest commit - https://github.com/socfortress/CoPilot/commit/33bc81131a2348db4e465282bf5d7994e3bc3b75 - allows you to manually set the Velociraptor ID
