### ISSUE TITLE
Agents unable to be deleted

### ISSUE THREAD

**Issue by kmendell** [socfortress/CoPilot#210]
**Describe the bug**
When trying to delete agents from copilot it errors out saying it cant find the velociraptor agent and failed to delete it. 
Even if i manually delete the agents from velo and wazuh they still show up in copilot. 

**To Reproduce**

1. Cick Agents 
2. Try to delete a Agent

or

1. Manually delete agents from Velo and Wazuh 
2. Try to sync agents 

**Expected behavior**
Agents should be removed from the list when deleted. 

**Screenshots**
![image](https://github.com/socfortress/CoPilot/assets/25576967/e4cbefb7-82e5-4511-943c-20f42f6ff81b)

\*\*Container Logs

copilot-mysql-1     | 2024-05-12T20:29:11.117928Z 6 [Note] Aborted connection 6 to db: 'copilot' user: 'copilot' host: '10.1.0.4' (Got an error reading communication packets)
copilot-backend-1   | 2024-05-12 20:29:12.670 | INFO     | app.db.db_session:get_db_session:181 - DB session created
copilot-backend-1   | 2024-05-12 20:29:12.670 | INFO     | app.agents.routes.agents:get_agents:108 - Fetching all agents
copilot-backend-1   | 2024-05-12 20:29:12.685 | INFO     | app.db.db_session:get_db_session:189 - Closing DB session
copilot-backend-1   | 2024-05-12 20:31:55.115 | INFO     | app.db.db_session:get_db_session:181 - DB session created
copilot-backend-1   | 2024-05-12 20:31:55.115 | INFO     | app.agents.routes.agents:delete_agent:454 - Deleting agent 022
copilot-backend-1   | 2024-05-12 20:31:55.115 | INFO     | app.agents.wazuh.services.agents:delete_agent_wazuh:125 - Deleting agent 022 from Wazuh Manager
copilot-backend-1   | 2024-05-12 20:31:55.116 | INFO     | app.connectors.wazuh_manager.utils.universal:send_delete_request:303 - Sending DELETE request to /agents
copilot-backend-1   | 2024-05-12 20:31:55.116 | INFO     | app.connectors.wazuh_manager.utils.universal:create_wazuh_manager_client:85 - Getting Wazuh Manager authentication token
copilot-backend-1   | 2024-05-12 20:31:55.116 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Manager from database
copilot-backend-1   | 2024-05-12 20:31:55.118 | INFO     | app.connectors.wazuh_manager.utils.universal:create_wazuh_manager_client:92 - Verifying the wazuh-manager connection to URL_REDACTED
copilot-backend-1   | 2024-05-12 20:31:55.396 | DEBUG    | app.connectors.wazuh_manager.utils.universal:create_wazuh_manager_client:106 - Wazuh Authentication Token successful
copilot-backend-1   | 2024-05-12 20:31:55.396 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Manager from database
copilot-backend-1   | 2024-05-12 20:31:55.437 | INFO     | app.agents.routes.agents:delete_agent:457 - Client ID: C.7f008cc10a8259ad
copilot-backend-1   | 2024-05-12 20:31:55.437 | INFO     | app.connectors.velociraptor.utils.universal:execute_query:174 - Executing query: SELECT collect_client(client_id='server', artifacts=['Server.Utils.DeleteClient'], env=dict(ClientIdList='C.7f008cc10a8259ad',ReallyDoIt='Y')) FROM scope()
copilot-backend-1   | 2024-05-12 20:31:55.438 | ERROR    | app.connectors.velociraptor.utils.universal:execute_query:202 - Failed to execute query: 'UniversalService' object has no attribute 'stub'
copilot-backend-1   | 2024-05-12 20:31:55.438 | ERROR    | app.agents.velociraptor.services.agents:handle_exception:166 - Failed to delete client C.7f008cc10a8259ad:
copilot-backend-1   | 2024-05-12 20:31:55.438 | ERROR    | app.agents.velociraptor.services.agents:handle_exception:166 - Failed to delete client C.7f008cc10a8259ad:
copilot-backend-1   | 2024-05-12 20:31:55.438 | ERROR    | app.db.db_session:get_db_session:185 - Error during DB session:
copilot-backend-1   | 2024-05-12 20:31:55.438 | INFO     | app.db.db_session:get_db_session:189 - Closing DB session

**Comment by taylorwalton** [comment]
Hey @kmendell - Fix applied here: https://github.com/socfortress/CoPilot/commit/a7a9831f64707a3045d76436c968bf99dfe89fba 

Issue was I was not creating the Velociraptor client service properly...the flow should now work as expected:

1. Wazuh Agent Deleted 
2. Velo Client Deleted
3. Delete from Agents DB table


Please note that you will need to delete the agent from Copilot. If you were to delete the Agent via wazuh or velo directly, it will still exist within Copilot
