### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by ingramcomputers** [socfortress/CoPilot#215]
In the agent.conf templates, you reference several scripts:

- open_audit.cmd
- install_dll.ps1
- clear_active_responses_logs.ps1
- open-audit.sh
- open-audit-osx.sh

Are you going to make these available? 
If not, I understand.

**Comment by taylorwalton** [comment]
Hey @ingramcomputers yes those referenced scripts are currently baked into our Windows installer that we provide to our clients. If you are interested in our assistance to create a Windows package tailored to your environment with these bundled scripts then shoot me an email at `taylor.walton@socfortress.co` and I'd be happy to discuss our service hour packages.
