### ISSUE TITLE
Feature Request: Allow the Ability to Upgrade Wazuh Agents in CoPilot

### ISSUE THREAD

**Issue by kmendell** [socfortress/CoPilot#219]
**Is your feature request related to a problem? Please describe.**
Not Related to a Problem.

**Describe the solution you'd like**
Inside of the CoPilot Console i think having the ability to upgrade the Wazuh Agents (either a one off, or all at once) as you can do this in Wazuh via the API or the console cli. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by taylorwalton** [comment]
Added in now 

Branch: https://github.com/socfortress/CoPilot/commit/95f21932ce66e2a77a801aa20438fd863f2b2f2d

![image](https://github.com/socfortress/CoPilot/assets/111797488/80a123b7-2dc2-4438-9fd7-4008e0c2bec5)
