### ISSUE TITLE
Alert fowarding not work

### ISSUE THREAD

**Issue by roomme13** [socfortress/CoPilot#221]
**Describe the bug**
Alert forwarding not work when test from graylog, get bad request 400 when try to test it

**To Reproduce**
Test notification "SEND TO COPILOT" in graylog

**Expected behavior**
able to forward alert from graylog to copilot

![image](https://github.com/socfortress/CoPilot/assets/1905950/e0cfb6d0-359d-422b-8729-29ede47d2c26)

**Comment by taylorwalton** [comment]
Hey @roomme13 - this is expected when trying to do a manual test via Graylog. Unfortunately, Graylog defaults to only being able to send a `GET` request when running a connection test, while the `api/monitoring_alert/create` endpoint only accepts `POST` requests. When Graylog actually sends an alert to CoPilot it does send a `POST` request which the API endpoint within Copilot then accepts. However, if you are seeing issues with this, then please open another issue and let me know
