### ISSUE TITLE
Wazuh Monitoring Alerts 'process_name' Error

### ISSUE THREAD

**Issue by 0lIvIa09** [socfortress/CoPilot#224]
**Describe the bug**
Wazuh monitoring alerts aren't being analysed and pushed to IRIS. Alerts were working fine until I pulled the latest images, with the recent changes. When they are invoked manually from the Pending Alerts tab I get an error pop up saying 'process_name'.

When checking one of the pending alerts in Graylog, it contained the field 'data_win_eventdata_image' with the value 'C:\\Windows\\System32\\svchost.exe'

**To Reproduce**

1. Go to 'Pending Alerts' tab under 'SOC'
2. Click on 'Invoke'
3. See error

**Expected behavior**
Wazuh monitoring alerts in the pending tab are automatically processed by Copilot and appear in IRIS.

**Screenshots**
Backend Logs:
![image](https://github.com/socfortress/CoPilot/assets/155996582/cf1918c9-c220-49d1-ba09-2c8e8d9a78e4)

**Comment by taylorwalton** [comment]
Hey @0lIvIa09 can you send the json payload of the alert?

**Comment by 0lIvIa09** [comment]
{
  "event_definition_id": "662f65513d0caf611bc20c79",
  "event_definition_type": "aggregation-v1",
  "event_definition_title": "WAZUH SYSLOG LEVEL ALERT",
  "event_definition_description": "Alert on Wazuh syslog level equal to ALERT",
  "job_definition_id": "6620e65672e07215657d9ebd",
  "job_trigger_id": "6656d550c47dce7bf40384ca",
  "event": {
    "id": "01HZ1K2G75ZQ108512GHFCC7ZT",
    "event_definition_type": "aggregation-v1",
    "event_definition_id": "662f65513d0caf611bc20c79",
    "origin_context": "urn:graylog:message:es:wazuh-emcel_34:a7318ef2-1d8a-11ef-8519-005056811c95",
    "timestamp": "2024-05-29T07:11:21.952Z",
    "timestamp_processing": "2024-05-29T07:12:16.101Z",
    "timerange_start": null,
    "timerange_end": null,
    "streams": [],
    "source_streams": [
      "662a28af033da75fa13da435"
    ],
    "message": "WAZUH SYSLOG LEVEL ALERT",
    "source": "graylog",
    "key_tuple": [],
    "key": "",
    "priority": 2,
    "scores": {},
    "alert": true,
    "fields": {
      "ALERT_ID": "a7318ef2-1d8a-11ef-8519-005056811c95",
      "ALERT_SOURCE": "WAZUH",
      "CUSTOMER_CODE": "emcel"
    },
    "group_by_fields": {},
    "replay_info": {
      "timerange_start": "2024-05-29T07:11:09.079Z",
      "timerange_end": "2024-05-29T07:12:09.079Z",
      "query": "syslog_level:ALERT AND syslog_type:wazuh AND NOT (rule_group1:office365 OR rule_group1:vulnerability-detector)",
      "streams": [
        "662a28af033da75fa13da435"
      ],
      "filters": []
    }
  },
  "backlog": []
}

**Comment by 0lIvIa09** [comment]
To be sure, this is the entire message in graylog?

**Comment by taylorwalton** [comment]
Wazuh-Indexer

**Comment by 0lIvIa09** [comment]
{
  "_index": "wazuh-emcel_34",
  "_id": "a7318ef2-1d8a-11ef-8519-005056811c95",
  "_version": 1,
  "_score": null,
  "_source": {
    "source_reserved_ip": true,
    "data_win_system_eventRecordID": "6853966",
    "data_win_eventdata_user": "xxxxxxx\\\\xxxxxxx",
    "agent_id": "495",
    "agent_name": "DT-2-3971",
    "gl2_remote_ip": "172.16.254.183",
    "data_win_system_eventID": "11",
    "gl2_remote_port": 58806,
    "agent_labels_customer": "emcel",
    "source": "172.16.254.183",
    "gl2_source_input": "662a2224033da75fa13d93ce",
    "rule_level": 14,
    "gl2_processing_timestamp": "2024-05-29 07:11:21.952",
    "data_win_system_task": "11",
    "timestamp_utc": "2024-05-29T07:11:21.652Z",
    "syslog_type": "wazuh",
    "data_win_system_threadID": "4904",
    "rule_description": "Suspicious executable file creation by rundll32: C:\\\\Users\\\\xxxxxxx\\\\AppData\\\\Roaming\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\Startup\\\\Monitor Ink Alerts - HP Officejet Pro 6830.lnk",
    "gl2_source_node": "ecb3ab62-be47-4e60-abf5-d32b2ecebbeb",
    "id": "1716966681.1016378580",
    "gl2_processing_duration_ms": 136,
    "rule_mitre_tactic": "Command and Control",
    "gl2_accounted_message_size": 4740,
    "data_win_eventdata_utcTime": "2024-05-29 07:11:21.646",
    "streams": [
      "662a28af033da75fa13da435"
    ],
    "rule_mitre_id": "T1105",
    "gl2_message_id": "01HZ1K0VB0264T7MCRD7MKNJY9",
    "data_win_system_computer": "xxxxxxx",
    "agent_ip_reserved_ip": true,
    "data_win_eventdata_ruleName": "technique_id=T1187,technique_name=Forced Authentication",
    "agent_ip": "xxxxxxx",
    "data_win_eventdata_image": "C:\\\\WINDOWS\\\\system32\\\\RunDll32.exe",
    "true": 1716966681.250694,
    "rule_groups": "sysmon, sysmon_eid11_detections, windows",
    "data_win_system_keywords": "0x8000000000000000",
    "data_win_system_level": "4",
    "process_id": "11064",
    "gl2_receive_timestamp": "2024-05-29 07:11:21.816",
    "data_win_system_severityValue": "INFORMATION",
    "data_win_eventdata_processGuid": "{d010fe1e-d519-6656-d701-000000007900}",
    "rule_mitre_technique": "Ingress Tool Transfer",
    "rule_firedtimes": 13,
    "data_win_system_systemTime": "2024-05-29T07:11:21.6524475Z",
    "rule_mail": true,
    "data_win_eventdata_creationUtcTime": "2022-12-20 13:59:35.588",
    "decoder_name": "windows_eventchannel",
    "data_win_system_processID": "4260",
    "data_win_system_channel": "Microsoft-Windows-Sysmon/Operational",
    "syslog_level": "ALERT",
    "data_win_system_providerName": "Microsoft-Windows-Sysmon",
    "data_win_eventdata_processId": "11064",
    "data_win_system_version": "2",
    "data_win_system_providerGuid": "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
    "timestamp": "2024-05-29 07:11:21.952",
    "cluster_name": "wazuh",
    "data_win_system_opcode": "0",
    "data_win_eventdata_targetFilename": "C:\\\\Users\\\\xxxxxxx\\\\AppData\\\\Roaming\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\Startup\\\\Monitor Ink Alerts - HP Officejet Pro 6830.lnk",
    "gl2_processing_error": "Replaced invalid timestamp value in message <a7318ef2-1d8a-11ef-8519-005056811c95> with current time - Value <2024-05-29T07:11:21.243+0000> caused exception: Invalid format: \"2024-05-29T07:11:21.243+0000\" is malformed at \"T07:11:21.243+0000\".",
    "message": "{\"true\":1716966681.250694,\"timestamp\":\"2024-05-29T07:11:21.243+0000\",\"rule\":{\"level\":14,\"description\":\"Suspicious executable file creation by rundll32: C:\\\\\\\\Users\\\\\\\\xxxxxxx\\\\\\\\AppData\\\\\\\\Roaming\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Start Menu\\\\\\\\Programs\\\\\\\\Startup\\\\\\\\Monitor Ink Alerts - HP Officejet Pro 6830.lnk\",\"id\":\"92211\",\"mitre\":{\"id\":[\"T1105\"],\"tactic\":[\"Command and Control\"],\"technique\":[\"Ingress Tool Transfer\"]},\"firedtimes\":13,\"mail\":true,\"groups\":[\"sysmon\",\"sysmon_eid11_detections\",\"windows\"]},\"agent\":{\"id\":\"495\",\"name\":\"DT-2-3971\",\"ip\":\"xxxxxxx\",\"labels\":{\"customer\":\"emcel\"}},\"manager\":{\"name\":\"wazuh-worker2\"},\"id\":\"1716966681.1016378580\",\"cluster\":{\"name\":\"wazuh\",\"node\":\"wazuh-worker2\"},\"decoder\":{\"name\":\"windows_eventchannel\"},\"data\":{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Sysmon\",\"providerGuid\":\"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}\",\"eventID\":\"11\",\"version\":\"2\",\"level\":\"4\",\"task\":\"11\",\"opcode\":\"0\",\"keywords\":\"0x8000000000000000\",\"systemTime\":\"2024-05-29T07:11:21.6524475Z\",\"eventRecordID\":\"6853966\",\"processID\":\"4260\",\"threadID\":\"4904\",\"channel\":\"Microsoft-Windows-Sysmon/Operational\",\"computer\":\"xxxxxxx\",\"severityValue\":\"INFORMATION\",\"message\":\"\\\"File created:\\r\\nRuleName: technique_id=T1187,technique_name=Forced Authentication\\r\\nUtcTime: 2024-05-29 07:11:21.646\\r\\nProcessGuid: {d010fe1e-d519-6656-d701-000000007900}\\r\\nProcessId: 11064\\r\\nImage: C:\\\\WINDOWS\\\\system32\\\\RunDll32.exe\\r\\nTargetFilename: C:\\\\Users\\\\xxxxxxx\\\\AppData\\\\Roaming\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\Startup\\\\Monitor Ink Alerts - HP Officejet Pro 6830.lnk\\r\\nCreationUtcTime: 2022-12-20 13:59:35.588\\r\\nUser: xxxxxxx\\\\xxxxxxx\\\"\"},\"eventdata\":{\"ruleName\":\"technique_id=T1187,technique_name=Forced Authentication\",\"utcTime\":\"2024-05-29 07:11:21.646\",\"processGuid\":\"{d010fe1e-d519-6656-d701-000000007900}\",\"processId\":\"11064\",\"image\":\"C:\\\\\\\\WINDOWS\\\\\\\\system32\\\\\\\\RunDll32.exe\",\"targetFilename\":\"C:\\\\\\\\Users\\\\\\\\xxxxxxx\\\\\\\\AppData\\\\\\\\Roaming\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\Start Menu\\\\\\\\Programs\\\\\\\\Startup\\\\\\\\Monitor Ink Alerts - HP Officejet Pro 6830.lnk\",\"creationUtcTime\":\"2022-12-20 13:59:35.588\",\"user\":\"xxxxxxx\\\\\\\\xxxxxxx\"}}},\"location\":\"EventChannel\"}",
    "rule_id": "92211",
    "manager_name": "wazuh-worker2",
    "cluster_node": "wazuh-worker2",
    "location": "EventChannel",
    "rule_group3": "windows",
    "data_win_system_message": "\"File created:\r\nRuleName: technique_id=T1187,technique_name=Forced Authentication\r\nUtcTime: 2024-05-29 07:11:21.646\r\nProcessGuid: {d010fe1e-d519-6656-d701-000000007900}\r\nProcessId: 11064\r\nImage: C:\\WINDOWS\\system32\\RunDll32.exe\r\nTargetFilename: C:\\Users\\xxxxxxx\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\Monitor Ink Alerts - HP Officejet Pro 6830.lnk\r\nCreationUtcTime: 2022-12-20 13:59:35.588\r\nUser: xxxxxxx\\xxxxxxx\"",
    "msg_timestamp": "2024-05-29T07:11:21.243Z",
    "rule_group2": "sysmon_eid11_detections",
    "rule_group1": "sysmon"
  },
  "fields": {
    "gl2_receive_timestamp": [
      "2024-05-29T07:11:21.816Z"
    ],
    "data_win_system_systemTime": [
      "2024-05-29T07:11:21.652Z"
    ],
    "gl2_processing_timestamp": [
      "2024-05-29T07:11:21.952Z"
    ],
    "timestamp_utc": [
      "2024-05-29T07:11:21.652Z"
    ],
    "msg_timestamp": [
      "2024-05-29T07:11:21.243Z"
    ],
    "timestamp": [
      "2024-05-29T07:11:21.952Z"
    ]
  },
  "highlight": {
    "agent_id": [
      "@opensearch-dashboards-highlighted-field@495@/opensearch-dashboards-highlighted-field@"
    ]
  },
  "sort": [
    1716966681952
  ]
}

**Comment by taylorwalton** [comment]
Thanks for sharing! I'm hoping this has been fixed in this commit : https://github.com/socfortress/CoPilot/pull/225/commits/1ab4b3863909eb71be6cda9db26ed98b69c63586

Please pull the latest images and try again

**Comment by 0lIvIa09** [comment]
Looks like it's working now. Thanks!
