### ISSUE TITLE
Copilot frontend container - Error  [emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)

### ISSUE THREAD

**Issue by pkul1997** [socfortress/CoPilot#226]
**Describe the bug**
The CoPilot front end container starts then almost immediately stops.  The containers log shows
`[emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)`

**To Reproduce**
Follow setup instructions

**Expected behavior**
Container to stay up and running

**Resolved by**
I was able to resolve the issue but just wanted to put something up in case anyone else runs into it.

The issue was caused by disabling ipv6 on my Ubuntu 22.04 Server, due to the nginx config trying to listen on IPv6 port [::]:80.
I was unable to find the nginx config file in the container to disable this so I will have to keep IPv6 enabled.

I re-nabled it by editing the grub file
`sudo vi /etc/default/grub`
set value `GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=0"`

**Comment by taylorwalton** [comment]
Thanks for that!
