### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by ioscanner** [socfortress/CoPilot#233]
The apt gpg key and source in docs doesn't work any longer.

curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg

echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list

Resolves the key and update of apt sources for Wazuh.

**Comment by taylorwalton** [comment]
Sorry but what documentation are you referring to? I dont see any documentation within Copilot that refers to installing Wazuh?

**Comment by ioscanner** [comment]
Most the docs you are using the old method of apt, it has changed to import the keys.  Just thought I would mention it.
https://socfortress.medium.com/part-1-wazuh-indexer-siem-backend-9b5ab37a477c
