### ISSUE TITLE
Timestamp Not found to Sort on for Alerts

### ISSUE THREAD

**Issue by kmendell** [socfortress/CoPilot#243]
**Describe the bug**
Alerts are not showing up in CoPilot as it cant find the timestamp field

I looked in Graylog and it does havea Timestamp field. 
<img width="271" alt="image" src="https://github.com/socfortress/CoPilot/assets/25576967/6e02b795-4527-42c4-a59a-f45792f43d85">

**To Reproduce**

Login to CoPilot
Click Alerts 
See the error

**Expected behavior**
Alerts show up 

**Screenshots**
<img width="780" alt="image" src="https://github.com/socfortress/CoPilot/assets/25576967/c53c3e11-645a-43cb-82df-83a72ab6fb95">

\*\*Container Logs

copilot-backend-1    | 2024-06-14 17:41:07.600 | WARNING  | app.connectors.wazuh_indexer.services.alerts:collect_alerts_generic:112 - An error occurred while collecting alerts: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [timestamp] in order to sort on')
copilot-backend-1    | 2024-06-14 17:41:07.600 | WARNING  | app.connectors.wazuh_indexer.services.alerts:collect_alerts_generic:124 - An error occurred while collecting alerts: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [timestamp] in order to sort on')
copilot-backend-1    | 2024-06-14 17:41:07.600 | WARNING  | app.connectors.wazuh_indexer.services.alerts:get_alerts_generic:186 - An error occurred while processing index .plugins-ml-config: An error occurred while collecting alerts: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [timestamp] in order to sort on')

**Comment by taylorwalton** [comment]
sounds like you upgraded to version 4.8 of wazuh

![image](https://github.com/socfortress/CoPilot/assets/111797488/0a5fb8ed-d0ca-41d6-a971-379064ce6feb)
