### ISSUE TITLE
Decommissioning a customer fails with dfir-iris

### ISSUE THREAD

**Issue by KoronGIT** [socfortress/CoPilot#265]
If you click on the "Decommission" button, the error message "Failed to delete customer: please remove the user from the iris customer within DFIR-IRIS" appears. This message also appears if you have manually removed the user from DFIR-IRIS. It blocks the entire decommission process.

2024-07-03 06:32:51.823 | INFO     | app.connectors.dfir_iris.utils.universal:create_dfir_iris_client:102 - Creating session with DFIR-IRIS.
2024-07-03 06:32:51.847 | INFO     | app.connectors.dfir_iris.utils.universal:fetch_and_parse_data:137 - Executing delete_customer... on args: (4,) and kwargs: {}
2024-07-03 06:32:51.859 | ERROR    | app.connectors.dfir_iris.utils.universal:fetch_and_parse_data:144 - Failed to execute delete_customer: manage/customers/delete/4?cid=1 - Invalid Customer ID - 
2024-07-03 06:32:51.860 | ERROR    | app.customer_provisioning.services.dfir_iris:delete_customer:88 - Failed to delete customer: please remove the user from the iris customer within DFIR-IRIS 
2024-07-03 06:32:51.860 | ERROR    | app.db.db_session:get_db_session:185 - Error during DB session: 
2024-07-03 06:32:51.860 | INFO     | app.db.db_session:get_db_session:189 - Closing DB session
Copy to Local Clipboard	Request Remote Clipboard	Copy to Remote Clipboard
Clear

**Comment by ZoccoCss** [comment]
I'm having the same issue with one customer. 

I decommissioned other customers successfully.

**Comment by KoronGIT** [comment]
I've tried it several times now with newly created copilots. It seems that the problem always occurs with the customer that is created first.

**Comment by taylorwalton** [comment]
@KoronGIT You need to remove the user from the Customer that exists within DFIR IRIS prior to deleting the customer within CoPilot.

![image](https://github.com/socfortress/CoPilot/assets/111797488/7bc1a5d9-f6f8-4d3b-b28c-a7c537de00f4)


Once the user is removed from the IRIS customer, you will then be able to decommission then delete the customer

**Comment by ZoccoCss** [comment]
![Screenshot_20240708_154359](https://github.com/socfortress/CoPilot/assets/47893772/e2c87cc2-9632-406f-b54f-7af3e7b03e73)
![Screenshot_20240708_154321](https://github.com/socfortress/CoPilot/assets/47893772/f231e0fd-1fec-4570-8c18-ad0725d901da)

I've removed the customer from Iris and still I haven't been able to decommission it.

**Comment by KoronGIT** [comment]
> @KoronGIT You need to remove the user from the Customer that exists within DFIR IRIS prior to deleting the customer within CoPilot.
> 
> ![image](https://private-user-images.githubusercontent.com/111797488/346588554-7bc1a5d9-f6f8-4d3b-b28c-a7c537de00f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Njg0OTksIm5iZiI6MTcyMDQ2ODE5OSwicGF0aCI6Ii8xMTE3OTc0ODgvMzQ2NTg4NTU0LTdiYzFhNWQ5LWY2ZjgtNGQzYi1iMjhjLWE3YzUzN2RlMDBmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxOTQ5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWI4NTNiMWQyOWU1OGRjMjQ5MDcxZTFlOGZmMWJmNmMxYmM0YmQ4MzY3YzhmNWRhOWUyNGE0OTQ5N2IxNjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9w4rF5LhlOvRVLz1RtX49wZi0RinpPyzjB-kycxFGno)
> 
> Once the user is removed from the IRIS customer, you will then be able to decommission then delete the customer

I did exactly as written in the start post and the error still occurs. The log extract is after manual removal.

**Comment by taylorwalton** [comment]
What is the IRIS customer name that this customer within copilot is tied to? is it that `montegrande soc` customer?

**Comment by ZoccoCss** [comment]
![Screenshot_20240708_170802](https://github.com/socfortress/CoPilot/assets/47893772/2910f36a-7896-4c82-8796-644d4b1bf24f)
I'm trying to delete "Prueba" Customer

**Comment by ZoccoCss** [comment]
I'm sorry, but I'm a bit confused. I followed the instructions that said to remove the customer from Iris after CoPilot failed to do it.

**Comment by taylorwalton** [comment]
Sorry if the instructions weren't clear but rather than deleting the Customer from IRIS you just need to remove the Customer from the User. Essentially its an access control that is built into IRIS and IRIS wont allow for Customer removal if a user still has access to that Customer

**Comment by ZoccoCss** [comment]
I created a new customer with the same name in Iris to see if Copilot would use it but it didn't work.

**Comment by taylorwalton** [comment]
Creating a new customer within IRIS with the same name will not work...IRIS references customers via an ID (which is also what is stored within CoPilot). IRIS increments this ID for every new customer so your newly created customer will have a different ID than the last one

**Comment by ZoccoCss** [comment]
I could manipulate the mySQL database to reflect the new IRIS ID or is there a simpler way?

**Comment by taylorwalton** [comment]
Correct, at the moment you would need to make a sql statement into the database. Table name is `customersmeta` and the column name is `customer_meta_iris_customer_id` which is an INT

**Comment by ZoccoCss** [comment]
I made the modification to the database and it successfully deleted the IRIS customer but not in Copilot. I guess the reason is that I had already deleted the Graylog Stream and the Wazuh Index. 

I believe I have two options at this stage, either create a new index and stream and modify the appropriate ids in the database or delete the record in the customers and customersmeta tables.

**Comment by taylorwalton** [comment]
I wouldnt recommend deleting the tables but perhaps the entries for that customer in the tables

**Comment by ZoccoCss** [comment]
Yes, I meant deleting the entry. 

I deleted the entry in the customersmeta table and then I was able to delete de customer in Copilot. 

Thank you, I no longer have the customer in the list and the rest of the app is working fine.
