### ISSUE TITLE
copilot-app container not found

### ISSUE THREAD

**Issue by Nabeel-Falconi** [socfortress/CoPilot#276]
I didn't find the copilot-app container. how to get admin credentials.
![image](https://github.com/user-attachments/assets/1763f5d3-cc5c-4f33-88a9-9372ef0e1d58)

**Comment by taylorwalton** [comment]
Hey @Nabeel-Falconi Sorry to hear the app is not starting as expected. 

It looks like you cloned the CoPilot repo. Was that intended?

If you are just looking to run the app and not make your own images, you can simply use our prebuilt images that are already apart of our docker-compose.yml file: https://github.com/socfortress/CoPilot/blob/main/docker-compose.yml

The above method does not require you to clone the repo and build your own images.
