### ISSUE TITLE
Graylog Connector: Sometimes http status code is 200 but there is no returned content

### ISSUE THREAD

**Issue by ngocngoan** [socfortress/CoPilot#277]
**Describe the bug**
When I send an HTTP POST request to the Graylog API **_/api/entitylists/preferences/saved-searches_**, then the error happens:

> 500: Failed to send POST request to /api/entitylists/preferences/saved-searches with error: Expecting value: line 1 column 1 (char 0)

**To Reproduce**

1. Import function **send_post_request()** from [Graylog universal module](https://github.com/socfortress/CoPilot/blob/main/backend/app/connectors/graylog/utils/universal.py#L125)
2. Send HTTP POST request by instrustion
`response = await send_post_request(
            endpoint="/api/entitylists/preferences/saved-searches",
            data=preferences.model_dump(by_alias=True, exclude_unset=True, mode="json"),
        )`
3. The error shows in the log

> Failed to update saved search preference: 500: Failed to send POST request to /api/entitylists/preferences/saved-searches with error: Expecting value: line 1 column 1 (char 0)

4. See the following images:

**Screenshots**

![Screenshot 2024-08-29 163558](https://github.com/user-attachments/assets/ddbb0493-e592-445d-b6c0-2f3c56f461fd)

![Screenshot 2024-08-29 163608](https://github.com/user-attachments/assets/bf571124-236f-46a7-865a-dd7ba0f040b8)

![Screenshot 2024-08-29 163617](https://github.com/user-attachments/assets/2e432922-8cb6-4309-b83a-2d5dc6560b65)

5. The reason

The response text is empty string. It is the reason why the `response.json()` command generates the above error.

**Screenshots**

![Screenshot 2024-08-29 170322](https://github.com/user-attachments/assets/1016b1d1-822a-4dc4-8347-f27b69c4a6fe)

**Expected behavior**

Update [line 168](https://github.com/socfortress/CoPilot/blob/main/backend/app/connectors/graylog/utils/universal.py#L168) from `response.json()` to `response.json() if response.text else None`

**Container Logs**

```
Traceback (most recent call last):
  File "/path/to/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by taylorwalton** [comment]
Hey @ngocngoan Thanks for the in depth troubleshooting and recommended fix, that really helps! I understand that you are experiencing an issue when sending a POST to Graylog using the `send_post_request` function.

I have no problem implementing your recommend fix, and thanks for providing that. I am curious though as to what intention you have with fetching `/api/entitylists/preferences/saved-searches` from Graylog as we are not currently leveraging this Graylog endpoint within CoPilot. Could you think of a use case where it would make sense to add some frontend support for the API endpoint of `/api/entitylists/preferences/saved-searches`?
