### ISSUE TITLE
ZABBIX INTERGRATION

### ISSUE THREAD

**Issue by Machos65** [socfortress/CoPilot#285]
The project is very good is there a way you would integrate Zabbix with your system

**Comment by taylorwalton** [comment]
Hey @Machos65 - Thanks for the positive feedback on the project! It sounds like you see value in integrating with Zabbix. Right now, we leverage InfluxDB for our data handling, which aligns better with our current system architecture. 

We have some videos that could help ease your deployment of InfluxDB if you choose to do so!

https://youtu.be/1VoTVv-iDXQ?si=LoJo_7YHauoWt0TO

https://youtu.be/vt6M1SzNfjE?si=vEDl8gnlJ65jf6jV

**Comment by Machos65** [comment]
Thanks  for your concern
