### ISSUE TITLE
Data Adapters for Lookup Tables missing after Stack Provisioning

### ISSUE THREAD

**Issue by dLoProdz** [socfortress/CoPilot#295]
**Describe the bug**
I'm running Graylog inside a docker container which has a different working directory that a regular installation of Graylog. After customer provisioning under Lookup Tables > Data Adapters, I get several errors for files not found [/etc/graylog/nist_800_53_to_cui.csv, /etc/graylog/network_ports.csv, /etc/graylog/software_vendors.csv]. Not sure if these files should be crated as part of the user provisioning script and due to the difference in working directories and user permissions they did not, or if these files should have come pre-bundled with the graylog installation.

**To Reproduce**
Stack Provisioning from CoPilot dashboard succeeds with the exception of errors in the Lookup Tables' Data Adapters. As a result, these lookup tables are not working.

**Expected behavior**
If these files are being provisioned by CoPilot, is there a way to get these templates so I can manually add them to my docker instance and modify the file paths in the data adapters config?

**Screenshots**

![Screenshot 2024-09-16 113641](https://github.com/user-attachments/assets/85cf50c1-b48a-4287-ac14-4437bb826365)

**Comment by taylorwalton** [comment]
Hey there! No those files are not created as part of the provisioning. You can remove those lookup adapters if you'd like, or you can follow adding your own like done so here: https://discord.com/channels/871419379999469568/1200829736042111028/1224362653829304370
