### ISSUE TITLE
no connectors showing in new install 

### ISSUE THREAD

**Issue by jaoglesbee** [socfortress/CoPilot#296]
![image](https://github.com/user-attachments/assets/aebab255-1319-4b77-97f2-f5fb28c399b7)
after brining container up no connectors are showing,,.,,,l

**Comment by taylorwalton** [comment]
Hmm, havent seen that before....can you share your browser debug tools and load the connectors page again to see your response back

![image](https://github.com/user-attachments/assets/290d799a-afb4-4f91-acf7-d2bce771e893)

**Comment by jaoglesbee** [comment]
> Hmm, havent seen that before....can you share the logs at startup and your browser debug tools and load the connectors page again to see your response back
> 
> ![image](https://private-user-images.githubusercontent.com/111797488/368705791-290d799a-afb4-4f91-acf7-d2bce771e893.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDI4NTksIm5iZiI6MTcyNjc0MjU1OSwicGF0aCI6Ii8xMTE3OTc0ODgvMzY4NzA1NzkxLTI5MGQ3OTlhLWFmYjQtNGY5MS1hY2Y3LWQyYmNlNzcxZTg5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxMDQyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGU5ZWJjOWRhY2RmNWFmMDIzMjQyNjc0NWRlZjdlMTMzYjI1ODAwMDU3ODQyMDlmMDE2MzcyZjVhOWY4M2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SjrPzBr__7YP0y_7nvOjgrgyqfvgssVkYnTJr-dCW1M)

![image](https://github.com/user-attachments/assets/b64e15c3-53da-420f-9fed-e7208e4d93c2)


ok so here is the response, so it looks like its failing to connect to wazuh but not showing the connectors to allow me to modify the urls

**Comment by jaoglesbee** [comment]
this may have something to do with it, i had to modify the docker compose file because my wazuh multi node docker containers are already using the port 443 so i hade to change port to 447.. because my wazuh dashboard is at myip:443 so i modified copilot to be at myip:447...

**Comment by jaoglesbee** [comment]
the front end will not start unless i modify the 443 ip to something else in the compose file do to it already being used by wazuh..

**Comment by jaoglesbee** [comment]
![image](https://github.com/user-attachments/assets/dc3f2e8f-7330-454e-ab6a-47082cba65b4)

**Comment by jaoglesbee** [comment]
![image](https://github.com/user-attachments/assets/676392cb-4f03-4e9a-bd50-523b6eb2b207)
allowing me to run the containers...

**Comment by jaoglesbee** [comment]
so i have tried taking continers down several time with connectors not showing so can you please tell me where the config is located on the backend so i can remove my wazuh config because it seems like it is causing this error even though it is correct...

**Comment by jaoglesbee** [comment]
![image](https://github.com/user-attachments/assets/e70ec490-dbd6-4a4f-bdc3-048c5a5192ac)

**Comment by jaoglesbee** [comment]
so correct me if im wrong here but in all your videos you are saying that wazuh and copilot must be installed in the same enviornment which they are... but you are using known ports that wazuh uses so if i change this port i then cannot configure anything...

**Comment by jaoglesbee** [comment]
im having a hard time with your software for a few reasons.. you have many videos yes but not one that goes from start to finish on configuring your software.. you mention an api key is needed from chatgpt where does it go? how do we obtain it? in all the videos i have seen you metion a key once but no tutorial on where that goes.

**Comment by jaoglesbee** [comment]
also after completley wiping your software and re configuring it.. i am now getting the same error everyone else seems to be getting in the comments of your youtube video that has never been responded to which is when you grep the admin password to login you get no resposne.. went digging on the backend server but with no clear information on where anything is stored wasnt able to find any information so do you have any insight on that??

**Comment by jaoglesbee** [comment]
![image](https://github.com/user-attachments/assets/b61a62a6-e2f9-44a2-b1cd-82be2cc3091e)
okay i was able to get connectors to show up by removing all volumes and wiping everything and doing a fresh reinstall... so my question to you now is a few different things, first being in your video you mentioned an apikey from chatgpt turbo where does this key go?? next question is i had to change the port as mentioned above so i need clarification if that is going to affect me accessing the wazuh indexer and or manager. In my docker enviornmnet copilot is setup on a different network then my wazuh containers from the default docker compose file you made. Will this matter? if not i feel like i have one chance to get the ip and user login password for indexer and manager right before it fails so can you please tell me if that will be my docker container ip address for indexer and manager or will it be my host ip address with specific port?

**Comment by taylorwalton** [comment]
It sounds like you have a lot running on one VM! I recommend deploying another VM within the same network and running CoPilot on the new VM. Otherwise alterations to the port mappings could have unattended consequences but glad to see you got the containers started...so are you seeing the connectors now?

**Comment by jaoglesbee** [comment]
yews i have copilot up and running and connected wazuh manager and indexer! currently trying to connect [SOCFortress-Threat-Intel](https://github.com/socfortress/SOCFortress-Threat-Intel) but the api link ou have provided in there throws a 404 error is that not an option anymore? 

Also why i got you great product!! 

is there a way we can intergrate 365 into the soc fortress for monitoring without having to provision a customer and use graylog? i want to monitor my 365 but we do not use graylog.

**Comment by taylorwalton** [comment]
Happy to hear that...Our Threat Intel API only goes through CoPilot and Graylog (see video here: https://youtu.be/FJunzP2c_mQ?si=ut5DDKT9NgqTZRJa)

Unfortunately you will not be able to integrate O365 using CoPilot without the existence of Graylog. Graylog is utilized very significantly within the stack and is a core component. May I ask why you do not use Graylog?
