### ISSUE TITLE
Incident management alert filtering

### ISSUE THREAD

**Issue by AlertMasterX** [socfortress/CoPilot#298]
Create an option to allow more than one filter to be applied while viewing alerts. Ie search by Asset Name and Status

**Comment by AlertMasterX** [comment]
Along the same lines, having these clickable Open / Closed / Inprogress to quickly filter would be a nice quality of life.

![image](https://github.com/user-attachments/assets/5884de21-3ce8-4efb-99e7-bc0ab20dc5a4)

**Comment by taylorwalton** [comment]
Both addressed in merge https://github.com/socfortress/CoPilot/pull/304/commits
