### ISSUE TITLE
GrayLog 

### ISSUE THREAD

**Issue by jaoglesbee** [socfortress/CoPilot#300]
hello after your response i decided to go ahead and set graylog up.. i am running into an issue and IM REALLY hoping you could help me troubleshoot it

2024-09-20T13:15:32.855-05:00 ERROR [VersionProbe] Unable to retrieve version from Elasticsearch node: Hostname 172.20.0.177 not verified:
certificate: sha256/K9vzq2kGyqfSIxoXnyyr1h2Z/lOSSVHEqk17Ln3eTCY=
DN: CN=wazuh1.indexer, OU=Wazuh, O=Wazuh, L=California, C=US
subjectAltNames: [wazuh1.indexer]. - Hostname 172.20.0.177 not verified:
certificate: sha256/K9vzq2kGyqfSIxoXnyyr1h2Z/lOSSVHEqk17Ln3eTCY=
DN: CN=wazuh1.indexer, OU=Wazuh, O=Wazuh, L=California, C=US
subjectAltNames: [wazuh1.indexer].
2024-09-20T13:15:32.856-05:00 INFO [VersionProbe] Elasticsearch is not available. Retry https://github.com/socfortress/CoPilot/pull/23

this is what im getting from greylog after walking through your tutorial.. there was a step " Add RootCA to Keystore if using HTTPS for Wazuh-Indexer" i am not using https on wazuh, but i tried it without running these steps and was getting an error so i went ahead and ran through the steps anyways and now im getting this error CAN YOU PLEASE HELP?

**Comment by taylorwalton** [comment]
Please refer these type of questions to our Discord channel : https://discord.gg/UN3pNBzaEQ
