### ISSUE TITLE
Re-work the filtering for the Alerts Tab

### ISSUE THREAD

**Issue by dLoProdz** [socfortress/CoPilot#308]
**Is your feature request related to a problem? Please describe.**
Limiting alerts to maximum 20 on the alerts tab, paired with the time range limitation, greatly hinders the ability to investigate,

Lets say I want to look at an alert that triggered 7 hours ago, so the 6 hours time range filter wouldn't show it, hence I have to switch to the 12 hour filter. But if I already have 20 alerts in the last 6 hours then the alert that triggered 7 hours ago is completely inaccessible.
 

**Describe the solution you'd like**
Filter options should be given with inputs, and limits shouldn't be set, lets say I have 30 alerts in a specified timerange, I would be unable to see 10 of those alerts based on the current setup

**Describe alternatives you've considered**
Alerts for group
Option to NOT set a limit to the number of alerts displayed.

Time range
Provide an input box [ ] (field integer) with qualifier dropdown [minutes | hours | days]

**Comment by taylorwalton** [comment]
Hey there, it sounds like you are looking to load more alerts per page based on a filter. I am curious where you are getting the maximum of 20 alerts? Maybe you don't have the latest version of CoPilot? In the latest version you can load up to 100 per page and set multiple filters:

![image](https://github.com/user-attachments/assets/d2712eb5-6b75-4069-8e90-61837a058e2e)

**Comment by dLoProdz** [comment]
Hi, 

This is what I'm seeing on the filter selection:

![image](https://github.com/user-attachments/assets/521aeff9-cdd2-4b00-b3d1-af9db0c5de6a)

I also don't get an option to go to next page when there are more than the set maximum of 20.

Also getting inconsistent results when I search, for example, I know I received more than 20 alerts yesterday for client X, but if I filter for 20 alerts and 2 days I'm getting only 19 results, and then if I filter the same client to 20 alerts and 5 days I only get back 7 results.

**Comment by dLoProdz** [comment]
I was not aware of that separate config regarding the scheduler.

I tried to run it manually and got the following error message:
```
AuthorizationException(403, 'security_exception', 'no permissions for [indices:data/read/scroll/clear] and User [name=[username], backend_roles=[], requestedTenant=null]')
```

Will look into it and get back to you, thanks!

**Comment by dLoProdz** [comment]
Sure enough adding the needed permission to the copilot user role fixed the issue and the job ran successfully. Thanks a lot Taylor!

**Comment by dLoProdz** [comment]
On the note of completely removing the Alerts tab, will you then move the Exclude Rule functionality that connects with OpenAI to the Incident Response > Alerts tab? That would be greatly beneficial.
