### ISSUE TITLE
Docker: port 80 and 443

### ISSUE THREAD

**Issue by freeload101** [socfortress/CoPilot#310]
**Describe the bug**
Wazuh and SOCFortress CoPilot  both want port 80 and 443. What service should have what port ? currenty have CoPilot running on 4433 and 800 ?
https://github.com/freeload101/SCRIPTS/blob/b214f65a33431b3536494700022a4b39ed397a7a/Bash/SOCFortress_CoPilot_Fast.bash#L159

**Comment by taylorwalton** [comment]
Hey there, you can just expose 443! This is used by the "copilot-frontend" which is just Nginx at the end of the day.
