### ISSUE TITLE
Create a sock alert errors: Syslog type wazuh is not configured in the system

### ISSUE THREAD

**Issue by SecurityArsenal** [socfortress/CoPilot#311]
New install of CoPilot when I try to create a soc alert it errors:  Syslog type wazuh is not configured in the system 

I do have syslog defined in wazuh, but I suspect this is something else.

**Comment by taylorwalton** [comment]
Correct, you will need to define the source like in this video here: https://youtu.be/3p6qiH9UF8U?si=-eyrnx8m43x7t33J&t=628

**Comment by SecurityArsenal** [comment]
Yeah I figured that out.  You should return an error that makes more sense.

**Comment by taylorwalton** [comment]
I agree. What is an error message that would make sense to you?

**Comment by SecurityArsenal** [comment]
Could be as simple as "Incident Management: Sources must be configured"

**Comment by SecurityArsenal** [comment]
An FAQ of common errors might be good when I go thru updating the documentation.  I can make an FAQ of the common errors a person will encounter.

**Comment by taylorwalton** [comment]
I agree, a FAQ of common errors would be very useful for those just getting started. That would be very helpful if you could put that together. I sometimes struggle with assuming everyone knows what I know and overlook "simple" requirements...
