### ISSUE TITLE
Can't exclude rule in wazuh

### ISSUE THREAD

**Issue by SecurityArsenal** [socfortress/CoPilot#312]
New install of CoPilot can't Exclude rule in Wazuh:  Expecting value: line 1 column 1 (char 0)

10/01/2024 05:43
500
POST
http://domain/api/wazuh_manager/rule/exclude
Expecting value: line 1 column 1 (char 0)
Type
Error
#1
/
admin

**Comment by taylorwalton** [comment]
Hey there, can you show the data that is being posted to the api endpoint?

**Comment by SecurityArsenal** [comment]
First let me confirm is this module still required (I do have it installed and the API key in the .env):      
    copilot-ai-module:
       image: ghcr.io/socfortress/copilot-ai-module:latest
       env_file: .env

I have tons of changes coming for the install of the current build doc. Once, I confirm everything is working I will run thru it a few more times, then plan to finish the installer for the current docker files needed, setup wazuh, graylog, shuffle, etc.  So users can just pull the script and run the installer.  It will ask if they want to install on more than one server.   If they do, It will ask for the host and creds to create the SSH keys so it can deploy everything on each system as needed.   Next, I would like to rewrite the copilot-ai-module so it will actually modify the wazah exclude file and restart wazuh.  This will save lots of time.  Might be good to be able to also prompt: global ignore, or this host only as it builds the exclude rule.  Then, I want to tie AI into monitoring the alerts and have it be able to run commands on the host to confirm alerts and pass it all into a case that it opens when it must investigate.

**Comment by taylorwalton** [comment]
Sounds like you are looking to do some exciting things with AI! Yes the `copilot-ai-module` image is required and runs this application: https://github.com/socfortress/CoPilot-AI-Module

Rewriting the copilot-ai-module to also modify the exclusion rule file is an idea that I had in mind as well but have not had time to explore. Do you have an idea as to how to ensure the newly created rule is compatible with Wazuh's regex syntax? This is the biggest challenge I see as Wazuh will fail to restart the service if there is a rule syntax issue. Excited to see what you come up with!

**Comment by SecurityArsenal** [comment]
I was thinking the same thing.  I don't know if they have a syntax checker.  Worse case if the system doesn't restart stop wazuh-manager comment out the new line and start it again.  I think I can write a basic check that will ensure it is not from format or other issues if it is wrong then send it back to AI to fix with the issue found.  I do this for another program does this for python and AI loves to screw up the format, so I beautify it first then check for missing / and other things that would cause it to break.    Providing a good strong prompt really does go a long way when making the request.

**Comment by SecurityArsenal** [comment]
Yeah looks like it is missing some code.  I am also having an issue with the new enterprise api keys. /usr/local/lib/python3.11/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:119: LangChainDeprecationWarning: The class `ChatOpenAI` was deprecated in LangChain 0.0.10 and will be removed in 0.3.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
/usr/local/lib/python3.11/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
2024-10-01 20:44:21.062 | DEBUG    | __main__:<module>:10 - Starting SOCFortress AI Module Application
2024-10-01 20:44:21.063 | INFO     | __main__:<module>:19 - Starting SOCFortress AI Module Application
INFO:     Started server process [8]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)

**Comment by SecurityArsenal** [comment]
I added that to the image and it works.  But the rule it provides prints all on a single line with /n between fields instead of printing in a format that can be cut and pasted.  This would be in how you at AI to present the format, or needs to be formatted before showing to the user.

**Comment by SecurityArsenal** [comment]
This is a duplicate of #305, But we should be able to tell AI in the prompt to output in the correct format and not use /n and put all in a single line.  This is a prompt issue and not telling it what format to output and ensure it formats it correctly and to ensure it escapes and not to modify the paths.
