### ISSUE TITLE
graylog_0 showing in alerts

### ISSUE THREAD

**Issue by SecurityArsenal** [socfortress/CoPilot#314]
Where is this getting graylog_0 pulled from is there a way to disable it?  It pulls all the defined customers indexes, but it also keeps pulling the graylog_0.  Is that correct, because it seems to have customer alerts in that index also.  I don't remember it doing that on the past version?

**Comment by taylorwalton** [comment]
Can you explain further what you are referring to?

**Comment by SecurityArsenal** [comment]
When in the Alerts tab graylog_0 is showing alerts for all customers as well as the index for each customer that has been provisioned.  This was not there in earlier versions.  This is a new install.

**Comment by taylorwalton** [comment]
Correct. We are leveraging Graylog's Alert feature to allow users to define their own alerting criteria. See around the 8:00 mark in this video where I explain this further: https://youtu.be/3p6qiH9UF8U?si=itCjYV6KRr0WaEQR
