### ISSUE TITLE
DFIR-IRIS Connector is not shown at the Connectors window

### ISSUE THREAD

**Issue by john-requejo-driscolls** [socfortress/CoPilot#333]
**Describe the bug**

I am unable to integrate my DFIR-IRIS platform with my CoPilot instance because the DFIR-IRIS connector does not appear in the connectors section. After reviewing the code, I noticed that there is no dedicated section for the DFIR-IRIS connector, unlike the other connectors.

**To Reproduce**

1. Go to the connectors "view"
2. Observe that the DFIR-IRIS connector is missing from the list of available connectors.

**Expected behavior**

The DFIR-IRIS connector should appear in the connectors section, allowing me to configure the necessary settings for integration, as is the case with other connectors.

**Screenshots**

![image](https://github.com/user-attachments/assets/8a5dc378-f8cf-423e-b697-4a7c23b76b42)

@taylorwalton

**Comment by taylorwalton** [comment]
Hey @john-requejo-driscolls - Thanks for checking out CoPilot! Correct, we no longer support DFIR-IRIS. We have replaced it with our own Alert/Case management system built into CoPilot. You can find out more in this video: https://youtu.be/3p6qiH9UF8U?si=FikII702-78h-Gun
