### ISSUE TITLE
Issue in the graylog

### ISSUE THREAD

**Issue by vamsi10101996** [socfortress/CoPilot#340]
Hi Team,

We are trying to do installation and configuration process of wazhu, graylog, mongodb, socfortres etc in the local virtual machine.  But we are getting an issue on the graylog after successful completion of wazhu process. 

We have tried to do in multiple debian versions even though we are getting the same error. So kindly suggest us how to do proceed and resolve the error.

Errors in the attached screenshots
![IMG-20241119-WA0003](https://github.com/user-attachments/assets/8d3e36bf-afc5-4e77-9403-2340f6530d22)
![IMG-20241119-WA0002(1)](https://github.com/user-attachments/assets/080c359e-e9a6-4677-9799-6fcefda46cd8)

**Comment by taylorwalton** [comment]
Hey there! Yes you will need to ensure that Graylog is connected to your Wazuh-Indexer. That error you are seeing within the Graylog web ui is known (https://community.graylog.org/t/elasticsearch-exception-reason-key-types-is-not-supported-in-the-metadata-section/27468/6) ...I recommend checking out an example config file to be used for the wazuh indexer here: https://github.com/socfortress/OSSIEM/blob/main/wazuh/config/wazuh_indexer/wazuh.indexer.yml
