### ISSUE TITLE
Error to create Source Configuration

### ISSUE THREAD

**Issue by nathanVader** [socfortress/CoPilot#350]
I have a problem with config of Incident Management... I only have connectors with Wazuh Indexer and Wazuh Manager verified.
When I try to create Source Configuration I get the following error and no sources appear to select:

![image](https://github.com/user-attachments/assets/06e58431-9c74-432b-ba43-3334dd865a6b)

This is the log of the backend when I try to create Source Configuration:

![image](https://github.com/user-attachments/assets/f94b0b17-b12b-48df-8ca6-f81bc35b6444)

**Comment by taylorwalton** [comment]
You also need to have Graylog connected...that API call that is failing is invoking Graylog
