### ISSUE TITLE
Ability to merge Incident Alerts

### ISSUE THREAD

**Issue by ioscanner** [socfortress/CoPilot#365]
I would like to request the ability to merge Incident Alerts by selecting them for alerts that belong together.  I know this can be done in each case, but that takes a long time if you have lots of alerts that go together in a single case.  Be nice to be able to select certain cases and merge them all into one.

**Comment by taylorwalton** [comment]
Hey There!

Thank you for sharing your feedback—it sounds like you’re looking for a more streamlined way to merge incident alerts into a single case when you have multiple related alerts. If I’m hearing you correctly, you’re saying that while CoPilot currently allows you to merge multiple alerts into a case, the process could be faster and more efficient when dealing with a high volume of alerts.

That’s an interesting perspective. To make sure I fully understand, could you clarify if you’re looking for a bulk selection option to merge multiple alerts into a case, or is there a specific workflow you’re envisioning? If you have examples or mockups that illustrate what you’re thinking, it would help me see how I might be able to improve the process for you.

**Comment by ioscanner** [comment]
Correct bulk selection on the main page.  So I select all the alerts I want to group into a case.  For now you select but can only delete.  This help if you have many alerts that connect to a single case and in the event it is lot of alert it would be nice to either search and select all to create new case with them all or merge many cases into one.  I think this could be in the NAV bar alerts, Incident Management - Alerts and cases  Because an event could be missed and need to be pulled into the case from NAV bar alerts as well as from Incident Management - Alerts.  If you really plan to use this for case work it needs to be able to search, select, merge, delete, and important - edit.
