### ISSUE TITLE
"Copilot Backend" failing to start on first install

### ISSUE THREAD

**Issue by PeatieFTW** [socfortress/CoPilot#381]
**Describe the bug**
ERROR: for copilot-backend  'ContainerConfig'

**To Reproduce**

Normal installation provided with guide.

mkdir CoPilot

wget https://raw.githubusercontent.com/socfortress/CoPilot/v0.1.2/docker-compose.yml

mkdir data

nano .env  (edited contents in the screenshot below)

docker compose up -d

**Expected behavior**

Expected it to run. I have admin credentials from the docker logs.  

**Screenshots**

![image](https://github.com/user-attachments/assets/46caa79f-cd8a-4741-a075-7a67e4a64f26)

![image](https://github.com/user-attachments/assets/936b35aa-e59c-4c1a-a16a-18906426660e)

(Passwords are not actually password1 I SWEAR 😂)

Frontend Logs

copilot-frontend_1       | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
copilot-frontend_1       | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
copilot-frontend_1       | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-copilot-ssl.sh
copilot-frontend_1       | Host is now https://localhost:
copilot-frontend_1       | TLS certificates found
copilot-frontend_1       | ... DH parameters found
copilot-frontend_1       | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend_1       | 2024/12/18 18:27:21 [emerg] 1#1: host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62
copilot-frontend_1       | nginx: [emerg] host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62
copilot-frontend_1       | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
copilot-frontend_1       | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
copilot-frontend_1       | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
copilot-frontend_1       | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
copilot-frontend_1       | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-copilot-ssl.sh
copilot-frontend_1       | Host is now https://localhost:
copilot-frontend_1       | TLS certificates found
copilot-frontend_1       | ... DH parameters found
copilot-frontend_1       | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend_1       | 2024/12/18 18:31:42 [emerg] 1#1: host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62
copilot-frontend_1       | nginx: [emerg] host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62
copilot-frontend_1       | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
copilot-frontend_1       | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
copilot-frontend_1       | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
copilot-frontend_1       | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
copilot-frontend_1       | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
copilot-frontend_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-copilot-ssl.sh
copilot-frontend_1       | Host is now https://localhost:
copilot-frontend_1       | TLS certificates found
copilot-frontend_1       | ... DH parameters found
copilot-frontend_1       | /docker-entrypoint.sh: Configuration complete; ready for start up
copilot-frontend_1       | 2024/12/18 18:39:56 [emerg] 1#1: host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62
copilot-frontend_1       | nginx: [emerg] host not found in upstream "copilot-backend" in /etc/nginx/conf.d/default.conf:62

Backend logs

9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.031 | INFO     | app.db.db_setup:ensure_scheduler_user:296 - Ensuring scheduler user exists
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.247 | INFO     | app.auth.services.universal:create_scheduler_user:157 - Added new scheduler user with username: scheduler
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.248 | INFO     | app.auth.services.universal:create_scheduler_user:158 - Scheduler user password: W4oz5pL1ttN
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.248 | INFO     | app.schedulers.scheduler:init_scheduler:82 - Initializing new scheduler...
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.266 | INFO     | app.schedulers.scheduler:init_scheduler:91 - Scheduling enabled jobs...
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.267 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.268 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.268 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.269 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.270 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.271 | INFO     | app.schedulers.scheduler:disable_job:187 - Job Metadata: None
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.273 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: agent_sync
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.274 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: resize_wazuh_index_fields
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.274 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: invoke_alert_creation_collect
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.274 | INFO     | app.schedulers.scheduler:schedule_enabled_jobs:242 - Scheduled job: invoke_sigma_queries_collect
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.275 | INFO     | app.schedulers.scheduler:init_scheduler:95 - Starting scheduler...
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.367 | INFO     | app.schedulers.scheduler:init_scheduler:97 - Scheduler started.
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.370 | INFO     | __main__:shutdown_scheduler:206 - Shutting down scheduler
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.370 | INFO     | __main__:shutdown_scheduler:210 - Scheduler is running, shutting down now...
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.370 | INFO     | app.db.db_setup:ensure_scheduler_user_removed:331 - Ensuring scheduler user exists
9c4e78d2f123_copilot_copilot-backend_1 | 2024-12-18 18:05:36.381 | INFO     | app.auth.services.universal:remove_scheduler_user:185 - Scheduler user removed.
9c4e78d2f123_copilot_copilot-backend_1 | Exception ignored in: <function Connection.__del__ at 0x7d49cf571da0>
9c4e78d2f123_copilot_copilot-backend_1 | Traceback (most recent call last):
9c4e78d2f123_copilot_copilot-backend_1 |   File "/opt/venv/lib/python3.11/site-packages/aiomysql/connection.py", line 1131, in __del__
9c4e78d2f123_copilot_copilot-backend_1 |   File "/opt/venv/lib/python3.11/site-packages/aiomysql/connection.py", line 339, in close
9c4e78d2f123_copilot_copilot-backend_1 |   File "/usr/lib/python3.11/asyncio/selector_events.py", line 864, in close
9c4e78d2f123_copilot_copilot-backend_1 |   File "/usr/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
9c4e78d2f123_copilot_copilot-backend_1 |   File "/usr/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
9c4e78d2f123_copilot_copilot-backend_1 | RuntimeError: Event loop is closed

**Comment by taylorwalton** [comment]
Hmm I've never seen that error related to `ContainerConfig` before as you show in your screenshot. Perhaps an issue related to your docker or docker compose version? I just ran an install for a client and used the latest version of docker and docker compose using these steps (https://docs.docker.com/engine/install/debian/) and had no issues. Could you try using those docker and docker compose install scripts?

**Comment by PeatieFTW** [comment]
That 100% worked.  I was using a depreciated version of docker compose.
