### ISSUE TITLE
Unable to add Customer

### ISSUE THREAD

**Issue by emmolab** [socfortress/CoPilot#388]
**Describe the bug**
Unable to add Customer to Copilot. Option Grayed out. Required connectors are setup and operating.

**To Reproduce**
Select Customers and attempt to select customer

**Expected behavior**
To be able to add customer

**Screenshots**
![Screenshot 2024-12-26 at 20-48-19 SOCFortress CoPilot](https://github.com/user-attachments/assets/060b929f-a132-47da-8f48-a73a18528a57)
![Screenshot 2024-12-26 at 20-47-44 SOCFortress CoPilot](https://github.com/user-attachments/assets/73787f24-c00f-4716-b633-72bbdfb289d5)
![Screenshot 2024-12-26 at 20-58-08 SOCFortress CoPilot](https://github.com/user-attachments/assets/c998231f-aeaa-4544-bbea-fc716b9e2eb9)
![Screenshot 2024-12-26 at 20-57-50 SOCFortress CoPilot](https://github.com/user-attachments/assets/8551a3a0-c011-4f78-9075-b428b0b36947)

\*\*Container Logs
ilot-backend          | 2024-12-26 12:54:06.767 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | /opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.40'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
copilot-backend          |   warnings.warn(
copilot-backend          | 2024-12-26 12:54:06.793 | INFO     | app.connectors.wazuh_indexer.utils.universal:resize_wazuh_index_fields:628 - Successfully resized the Wazuh index fields
copilot-backend          | 2024-12-26 12:54:06.821 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:40 - Updated job metadata with the last success timestamp.
copilot-backend          | 2024-12-26 12:54:06.821 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:55:06.792 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:24 - Resizing Wazuh index fields via scheduler...
copilot-backend          | 2024-12-26 12:55:06.792 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:55:06.793 | INFO     | app.connectors.utils:is_connector_verified:52 - Checking if connector Wazuh-Indexer is verified
copilot-backend          | 2024-12-26 12:55:06.797 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:29 - Wazuh Indexer connector is verified.
copilot-backend          | 2024-12-26 12:55:06.797 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:55:06.798 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Indexer from database
copilot-backend          | 2024-12-26 12:55:06.802 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | /opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.40'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
copilot-backend          |   warnings.warn(
copilot-backend          | 2024-12-26 12:55:06.828 | INFO     | app.connectors.wazuh_indexer.utils.universal:resize_wazuh_index_fields:628 - Successfully resized the Wazuh index fields
copilot-backend          | 2024-12-26 12:55:06.869 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:40 - Updated job metadata with the last success timestamp.
copilot-backend          | 2024-12-26 12:55:06.869 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:56:07.090 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:24 - Resizing Wazuh index fields via scheduler...
copilot-backend          | 2024-12-26 12:56:07.092 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:56:07.092 | INFO     | app.connectors.utils:is_connector_verified:52 - Checking if connector Wazuh-Indexer is verified
copilot-backend          | 2024-12-26 12:56:07.095 | INFO     | app.schedulers.services.invoke_alert_creation:invoke_alert_creation_collect:21 - Invoking alert creation collection via scheduler...
copilot-backend          | 2024-12-26 12:56:07.095 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:56:07.096 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:56:07.096 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Indexer from database
copilot-backend          | 2024-12-26 12:56:07.097 | INFO     | app.schedulers.services.invoke_sigma_queries:invoke_sigma_queries_collect:18 - Invoking sigma queries collection via scheduler...
copilot-backend          | 2024-12-26 12:56:07.097 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:56:07.109 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:29 - Wazuh Indexer connector is verified.
copilot-backend          | 2024-12-26 12:56:07.110 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:56:07.110 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Indexer from database
copilot-backend          | 2024-12-26 12:56:07.113 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:56:07.119 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | /opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.40'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
copilot-backend          |   warnings.warn(
copilot-backend          | 2024-12-26 12:56:07.152 | INFO     | app.incidents.services.alert_collection:get_alerts_not_created_in_copilot:65 - Indices: ['gl-events_0']
copilot-backend          | 2024-12-26 12:56:07.152 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:56:07.152 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Indexer from database
copilot-backend          | /opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.40'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
copilot-backend          |   warnings.warn(
copilot-backend          | 2024-12-26 12:56:07.179 | INFO     | app.connectors.wazuh_indexer.utils.universal:resize_wazuh_index_fields:628 - Successfully resized the Wazuh index fields
copilot-backend          | 2024-12-26 12:56:07.181 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:56:07.183 | INFO     | app.schedulers.services.invoke_sigma_queries:invoke_sigma_queries_collect:30 - Updated job metadata with the last success timestamp.
copilot-backend          | 2024-12-26 12:56:07.184 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:56:07.216 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:40 - Updated job metadata with the last success timestamp.
copilot-backend          | 2024-12-26 12:56:07.216 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:56:07.251 | INFO     | app.incidents.services.alert_collection:get_alerts_not_created_in_copilot:74 - Alerts not created: 0 alerts found
copilot-backend          | 2024-12-26 12:56:07.252 | INFO     | app.incidents.routes.incident_alert:create_alert_auto_route:157 - Alerts to create in CoPilot: alerts=[] success=True message='Success'
copilot-backend          | 2024-12-26 12:56:07.281 | INFO     | app.schedulers.services.invoke_alert_creation:invoke_alert_creation_collect:33 - Updated job metadata with the last success timestamp.
copilot-backend          | 2024-12-26 12:56:07.281 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:57:06.782 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:24 - Resizing Wazuh index fields via scheduler...
copilot-backend          | 2024-12-26 12:57:06.782 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:57:06.782 | INFO     | app.connectors.utils:is_connector_verified:52 - Checking if connector Wazuh-Indexer is verified
copilot-backend          | 2024-12-26 12:57:06.788 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:29 - Wazuh Indexer connector is verified.
copilot-backend          | 2024-12-26 12:57:06.788 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:57:06.788 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Indexer from database
copilot-backend          | 2024-12-26 12:57:06.793 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | /opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.40'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
copilot-backend          |   warnings.warn(
copilot-backend          | 2024-12-26 12:57:06.816 | INFO     | app.connectors.wazuh_indexer.utils.universal:resize_wazuh_index_fields:628 - Successfully resized the Wazuh index fields
copilot-backend          | 2024-12-26 12:57:06.865 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:40 - Updated job metadata with the last success timestamp.
copilot-backend          | 2024-12-26 12:57:06.866 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:57:30.191 | INFO     | app.connectors.velociraptor.routes.artifacts:get_all_artifacts:237 - Fetching all artifacts
copilot-backend          | 2024-12-26 12:57:30.191 | INFO     | app.connectors.velociraptor.services.artifacts:get_artifacts:80 - Fetching artifacts from Velociraptor
copilot-backend          | 2024-12-26 12:57:30.192 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Velociraptor from database
copilot-backend          | 2024-12-26 12:57:30.204 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:57:30.204 | INFO     | app.agents.routes.agents:get_agents:167 - Fetching all agents
copilot-backend          | 2024-12-26 12:57:30.212 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:57:33.499 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:57:33.518 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:58:06.757 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:24 - Resizing Wazuh index fields via scheduler...
copilot-backend          | 2024-12-26 12:58:06.757 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:58:06.757 | INFO     | app.connectors.utils:is_connector_verified:52 - Checking if connector Wazuh-Indexer is verified
copilot-backend          | 2024-12-26 12:58:06.762 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:29 - Wazuh Indexer connector is verified.
copilot-backend          | 2024-12-26 12:58:06.762 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:58:06.762 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Indexer from database
copilot-backend          | 2024-12-26 12:58:06.766 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | /opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.40'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
copilot-backend          |   warnings.warn(
copilot-backend          | 2024-12-26 12:58:06.789 | INFO     | app.connectors.wazuh_indexer.utils.universal:resize_wazuh_index_fields:628 - Successfully resized the Wazuh index fields
copilot-backend          | 2024-12-26 12:58:06.806 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:40 - Updated job metadata with the last success timestamp.
copilot-backend          | 2024-12-26 12:58:06.806 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | 2024-12-26 12:59:06.765 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:24 - Resizing Wazuh index fields via scheduler...
copilot-backend          | 2024-12-26 12:59:06.765 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:59:06.766 | INFO     | app.connectors.utils:is_connector_verified:52 - Checking if connector Wazuh-Indexer is verified
copilot-backend          | 2024-12-26 12:59:06.770 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:29 - Wazuh Indexer connector is verified.
copilot-backend          | 2024-12-26 12:59:06.770 | INFO     | app.db.db_session:get_db_session:60 - DB session created
copilot-backend          | 2024-12-26 12:59:06.771 | INFO     | app.connectors.utils:get_connector_info_from_db:29 - Fetching connector Wazuh-Indexer from database
copilot-backend          | 2024-12-26 12:59:06.775 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session
copilot-backend          | /opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.40'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
copilot-backend          |   warnings.warn(
copilot-backend          | 2024-12-26 12:59:06.794 | INFO     | app.connectors.wazuh_indexer.utils.universal:resize_wazuh_index_fields:628 - Successfully resized the Wazuh index fields
copilot-backend          | 2024-12-26 12:59:06.802 | INFO     | app.schedulers.services.wazuh_index_resize:resize_wazuh_index_fields:40 - Updated job metadata with the last success timestamp.
copilot-backend          | 2024-12-26 12:59:06.802 | INFO     | app.db.db_session:get_db_session:68 - Closing DB session

**Comment by ioscanner** [comment]
If you updated the add customer feature is now behind a paywall subscription.  Roll back to 12/10 or so date and it will work.  Not sure the exact date Taylor put the MSSP subscription.

**Comment by emmolab** [comment]
@ioscanner  thanks for this info. I've rolled back to an earlier release and I can now add customers. Cheers

**Comment by taylorwalton** [comment]
Hey @emmolab,

I completely understand how frustrating it might feel to encounter a license requirement when adding and provisioning more than one customer. It sounds like you value the flexibility to access all features, and I wish we could make the entire platform and its capabilities free for everyone. Unfortunately, we rely on these licenses to continue funding CoPilot’s ongoing development and to support the free content we provide to the community.

From what you’ve shared, it seems like you’re considering rolling back to an earlier version to avoid the licensing requirement. While that’s an option, I’d encourage you to consider a couple of things:
	•	Rolling back could mean missing out on critical fixes, updates, and the latest improvements to CoPilot.
	•	Over time, this could lead to challenges with compatibility or not having access to features that make managing multiple customers easier.

If flexibility is your main goal, I wanted to mention that clients who receive our Professional Services offering are provided with the MSSP Unlimited license as part of their CoPilot instance. This might be worth exploring if you’re interested in a more robust solution for managing your customers.
